### ISSUE TITLE
how to proceed

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#1]
1. make things work*
2. find out how to store PCA and friends in/with the `AnnData` https://github.com/theislab/scanpy/commit/1cec41881e6d65f489111971f36142cb34c6cf49#commitcomment-20744162
3. determine how to read/write `AnnData`. maybe fields named `var_*` in the HDF5 will be var metadata and so on?

---

*apart from things still crashing, especially the group plotting should be fixed (should probably be transformed to one `scatter` call with a list of all groups)

**Comment by falexwolf** [comment]
Good! So, I'd really like to jump in and work on ann_matrix as well, if you think this is efficient. Of course, I don't want to mess up what you had in mind.
1. yes, that's important - can i help?
2. that's easy, simply put it in smp as a multicolumn object
3. should be very easy as well, maybe recarray can directly be written with a single key, if not, one has to make the separation between str and float columns -> shall I attack that? see [this](https://github.com/theislab/scanpy/commit/ac79f8991953bf7f4ae33f243b384560c131a8f9#L650-L669) for how it was done with the ddata using its 'rowcat' attribute. should be straightforwardly adapted, right?*
---
*sorry, I simply forgot to add readwrite.py on thursday night, which caused master to be non-working since then, of course. with readwrite.py added, master now works just fine. I guess the only change you made to utils.py was adding the AnnData.from_dict(...) in the function read()? so one could use readwrite.py from master within ann_matrix. or just create readwrite.py again by cutting out everything related to reading/writing from utils and pasting it into the new module readwrite.py.

**Comment by falexwolf** [comment]
Generally: What shall I do in order to merge ann_matrix as quickly as possible with the master branch? Starting from tomorrow, fiona would like to work on one tool using the nestorowa16 case i mentioned before. So if you allow me, I'll try to get everything running and polished tonight. 
PS: During the day, I'll be offline.

**Comment by flying-sheep** [comment]
sure, go ahead, i’m occupied today preparing my mitarbeitergespräch :D

**Comment by falexwolf** [comment]
damn, I'm not fit enough to make ann_matrix work tonight. so, in order to get figures, analysis and a barebone code for fiona ready (we have a skype conference with fabian and the group in cambridge tomorrow at 11am, and fabian is quite pushy), i'll use the working master branch.

let's discuss merging with ann_matrix in person during the next days.
