### ISSUE TITLE
sc.tl.louvain not respecting n_jobs parameter

### ISSUE THREAD

**Issue by constantAmateur** [scverse/scanpy#101]
I'm assuming that the `n_jobs` parameter is supposed to control the number of simultaneously threads used in calculating clusters.  However, no matter what I set this parameter to the process will spawn as many threads as their are cores on the machine running it.

The offending bit of code seems to be a call to `graph.update.diffmap()` in `add_or_update_graph_in_adata` as far as I can tell.

I need to be able to control the number of threads used to use scanpy on a farm.  How can I do this?

Thanks.

**Comment by falexwolf** [comment]
Yes, I know about an issue that is probably related to that: At some point in `add_or_update_graph_in_adata`, numpy takes more cores than it's supposed to - that's the only instance in the whole of Scanpy. Otherwise it's well-behaved. When Scanpy 1.0 will be released in the next few days, this will be resolved.

Do you think this will do the job for you?

**Comment by constantAmateur** [comment]
Yes that will solve the problem.  Thank you, looking forward to the new version.
