### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by dawe** [scverse/scanpy#1121]
I've had hard time in figuring this out. This is not a problem of scanpy directly but apparently is related to [scikit-learn 0.21 series](https://github.com/scikit-learn/scikit-learn/issues/14485) which is a dependency of latest scanpy version (1.4.6). Also related to [this comment in pytorch](https://github.com/pytorch/pytorch/issues/2575#issuecomment-523657178). My issue is that I'm using, in addition to scanpy, another library performing a dl_import with static TLS. 
So if I issue
```python
import scanpy as sc
import graph_tool.all as gt
```
I get

```python
ImportError: dlopen: cannot load any more object with static TLS 
```
error and I'm not able to use the second library. Reversing the order of the imports raises the same error and I'm not able to use `scanpy`.

The issue is solved installing scikit-learn 0.20.4 (the last of 0.20 series). What are the exact scikit-learn 0.21.2 dependecies in scanpy?

**Comment by ivirshup** [comment]
It looks to me like the sklearn dependency was update more due to bugs in earlier 0.21.* releases series, see 7716bfdec3cb9bd19923a91180dabc35ffd7709a. We don't promise compatibility with older versions of sklearn, so downgrading is not a good long-term solution.

@Koncopd might also be able to give some advice on this, as I believe he has been using pytorch with scanpy, though I'm not sure if this is via conda environments.

**Comment by dawe** [comment]
Apparently this is solved on more recent OS... I was working on a 2.6 kernel.
