### ISSUE TITLE
BBKNN and ingest

### ISSUE THREAD

**Issue by vgiansanti** [scverse/scanpy#1122]
Hi all!
I want to use ingest after BBKNN but it gives an error related to the metric.
If I add the metric parameter to the neighbors dict I have no more problems, but it is true only if the metric is euclidean. 

Is it possible to have the metric always reported in the BBKNN neighbors dict? And to use ingest with different metrics?

**Comment by ivirshup** [comment]
BBKNN is an external tool, and feature requests for it should be directed to the bbknn authors: https://github.com/Teichlab/bbknn

**Comment by ivirshup** [comment]
BTW @vgiansanti and @martaint, you might be able to manually add the metric to the anndata object as a work around.

**Comment by yyoshiaki** [comment]
Hi,
I tried ingest using the reference made with BBKNN. As @ivirshup said, ingest was worked by adding `adata_ref.uns['neighbors']['params']['metric'] = 'euclidean'`. However, the result was quite poor.

![image](https://user-images.githubusercontent.com/19543497/117822090-2aaa0480-b2a7-11eb-80ea-a31240861a4b.png)

In contrast, if I merge all datasets (eg references and query), it worked well, but when we want to take over the reference embedding, I actually want to use ingest rather than run bbknn again. Is there any option to feed in this case? or should I ask this in the BBKNN repo?

![image](https://user-images.githubusercontent.com/19543497/117822235-562cef00-b2a7-11eb-875f-262452baff0d.png)

This is the notebook can reproduce the problem.
https://nbviewer.jupyter.org/github/yyoshiaki/ingest_after_bbknn/blob/main/notebook.ipynb
https://github.com/yyoshiaki/ingest_after_bbknn/blob/main/notebook.ipynb
