### ISSUE TITLE
Distorted UMAP aspect ratio in certain adata subsets

### ISSUE THREAD

**Issue by sfortma2** [scverse/scanpy#1141]
Hi,
I seem to be running into a problem where UMAP projections for my subsetted adata appear distorted, but only for certain clusters. I'm not sure if this is actually a bug or if the function is behaving properly. Oddly, some subsets appear 'undistorted' such that their UMAP projections are identical to that of the original unsubsetted adata. However, other subsets appear distorted compared to the original unsubsetted adata, such that their aspect ratios seem to have changed slightly. Please see below. Is this a bug or am I not passing the correct options? Any guidance would be greatly appreciated, and my apologies if this belongs in the community thread.

## Distorted example ##
`sc.pl.umap(adata, color='louvain_r0.8_sub1', palette=sc.pl.palettes.vega_20_scanpy, groups=['2','3','4','5','6','7','8','9'])`
![image](https://user-images.githubusercontent.com/56206488/78223316-49c34980-748c-11ea-8f96-171c39444d87.png)
`ec = adata[adata.obs['louvain_r0.8_sub1'].isin(['2','3','4','5','6','7','8','9']),:].copy()`
`sc.pl.umap(ec, color='louvain_r0.8_sub1', palette=sc.pl.palettes.vega_20_scanpy)`
![image](https://user-images.githubusercontent.com/56206488/78223415-711a1680-748c-11ea-8a02-b02c5701d911.png)

## Undistorted example ##
`sc.pl.umap(adata, color='louvain_r0.8_sub1', palette=sc.pl.palettes.vega_20_scanpy, groups=['11'])`
![image](https://user-images.githubusercontent.com/56206488/78223506-9a3aa700-748c-11ea-9608-f4fa8ba4e34c.png)
`tc = adata[adata.obs['louvain_r0.8_sub1'].isin(['11']),:].copy()`
`sc.pl.umap(tc, color='louvain_r0.8_sub1', palette=sc.pl.palettes.vega_20_scanpy)`
![image](https://user-images.githubusercontent.com/56206488/78223568-b9d1cf80-748c-11ea-93f8-0d0e9138f0bf.png)

#### Versions:
scanpy==1.4.4.post1 anndata==0.7.1 umap==0.3.10 numpy==1.18.1 scipy==1.3.0 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.8.0 louvain==0.6.1

Best,
Seth

**Comment by LuckyMD** [comment]
Hi @sfortma2 ,

There are two things going on here as far as I can tell.
1. The colours are not consistent after subsetting, and
2. The x- and y-axes are "distorted" as you put it.

For point 1, I recently saw a PR for this... so I assume it has been fixed in master, or is being fixed at the moment.

For point 2, this is a normal result of subsetting the data. The data points in your second cluster span a similar x-axis and y-axis range. Thus, as the subsetted object is displayed in a square plot it looks similar. In your first cluster, the y-axis range the data points span is greater than the x-axis range, so the plot looks pulled apart in the x-axis. You can try to counteract this by changing the figure size to be higher than it is wide. I believe you should be able to pass a `figsize=(x,y)` parameter to the function. Otherwise you can work with `rcParams['figure.figsize'] = (x,y)`.

**Comment by sfortma2** [comment]
Thanks for the explanation and solution Malte! Altering the rcParams setting works well and solves the problem (see below). Much appreciated.
`rcParams['figure.figsize'] = (4,6)`
`sc.pl.umap(ec, color='louvain_r0.8_sub1', palette=sc.pl.palettes.vega_20_scanpy)`
![image](https://user-images.githubusercontent.com/56206488/78280867-62a91a80-74df-11ea-8e0e-314797f78152.png)
