### ISSUE TITLE
Making `scores` parameterized

### ISSUE THREAD

**Issue by HypoChloremic** [scverse/scanpy#1152]
https://github.com/theislab/scanpy/blob/2a7fb7cdf56ff44ef6338c7dba3b84b4b32d216c/scanpy/plotting/_tools/__init__.py#L286

`scanpy.pl.rank_genes_groups()` by default presents the `scores` from `adata.uns['rank_genes']['scores']`. However, why is it not possible to change to `scores`  `logfoldchanges`. The code at line 286 does not use any modularity or possible parameterization. A possible change would be to introduce a new parameter `plotby`, which corresponds to `adata.uns['rank_genes'][f'{plotby}']` or similar. 

I do realize that it is easy to extract the relevant data and plot them by myself. However, there is value in making it easier to choose what to exactly plot from the `rank_genes_groups`

**Comment by LuckyMD** [comment]
I think the plotting parameter would make a lot of sense. We should take a few things into account though when determining defaults here.
1. Not all methods have log fold changes (`'logreg'` for example)
2. Ordering based on log FC will be different than based on the scoring (lowly expressed genes will typically have higher logFC). I'm not sure how meaningful the plot would then be...
3. We initially didn't have any fold changes or p-values at all, partially because the marker gene DE test setup is ill-defined. You test gene in two groups where the groups are defined based on the genes you test... that will generate inflated p-values. Hence it might be a good idea to only consider the test as a way to order genes rather than a robust statistical test.

**Comment by gokceneraslan** [comment]
> * Not all methods have log fold changes (`'logreg'` for example)

This will hopefully be fixed: https://github.com/theislab/scanpy/pull/1081#discussion_r393315428

**Comment by LuckyMD** [comment]
> This will hopefully be fixed: [#1081 (comment)](https://github.com/theislab/scanpy/pull/1081#discussion_r393315428)

Interesting... a logFC is not sth that comes naturally out of a logistic regression model, no? Sergei would have to add a separate calculation.

**Comment by gokceneraslan** [comment]
I think FC should be reconsidered and provided as a method-agnostic metric.
