### ISSUE TITLE
trackplot enhancement 

### ISSUE THREAD

**Issue by rsggsr** [scverse/scanpy#1195]
Hi,

I am recently playing around with trackplot and would like to see if there's more arguments I could manually edit the trackplot. 

I am wondering if 1) we could change the order of cluster in the x axis.
                             2) we could change the peak shape to the bar shape so make it crowded.
                             3) we could add a mean (black line) within each cluster so there would be a 
                                 discontinuous horizontal black line across clusters.

I am trying to get this done by looking into the code but still welcome any help!!
Thanks!

**Comment by fidelram** [comment]
For 1) the order is given by pandas categories order of the .obs data frame. The order can be changed using `reorder`  https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#reordering

For 2) I am not so sure what you mean and for 3) The best is get each of the axes and modified it as you want afterwards. For this, set `show=False`.

**Comment by eroell** [comment]
As we haven't heard back after the followup we will close the issue at this point I think, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
