### ISSUE TITLE
filter_rank_genes_groups condition should be OR instead of AND

### ISSUE THREAD

**Issue by nhyda** [scverse/scanpy#1213]
here is the code for marker filter
I think the 3 condition need to be OR instead of AND
gene_names = gene_names[
        (fraction_in_cluster_matrix > min_in_group_fraction) &
        (fraction_out_cluster_matrix < max_out_group_fraction) &
        (fold_change_matrix > min_fold_change)
    ]

```python
...
```

```pytb
...
```

#### Versions:

> ...

**Comment by racng** [comment]
It makes sense to use AND logic, because the function keeps genes that satisfy all three conditions. 
1) Fraction of cells inside the cluster expressing the gene must be greater than `min_in_group_fraction`
2)  Fractions of cells outside the cluster expressing the gene must be less than `max_out_group_fraction`
3) Fold change must be greater than `min_fold_change`

But there are remaining issues (calculation of fold change and using the absolute value of the fold change) in this function that needs to be updated #863

**Comment by nhyda** [comment]
Thanks for clarification. I had thought it is for filtering out genes.

**Comment by fidelram** [comment]
After https://github.com/theislab/scanpy/pull/1156 I will update the function.

**Comment by brianpenghe** [comment]
> After #1156 I will update the function.

Wait, does it use OR logic now?? Doesn't AND logic make more sense???
