### ISSUE TITLE
Recent changes in sc.tl.rank_genes_groups broke y-axis range in sc.pl.rank_genes_groups

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#1335]
y-axis range of sc.pl.rank_genes_groups seems unnecessarily long:

![image](https://user-images.githubusercontent.com/1140359/88754278-41bea200-d12c-11ea-9d8c-aeb013ea6a02.png)

```python
import scanpy as sc

sc.set_figure_params(dpi=72)
adata = sc.datasets.paul15()
sc.pp.log1p(adata)
sc.tl.rank_genes_groups(adata, groupby='paul15_clusters', method='t-test')
sc.pl.rank_genes_groups(adata, sharey=False)
```

#### Versions:

scanpy==1.5.2.dev52+g10937f5f anndata==0.7.4 umap==0.4.6 numpy==1.19.0 scipy==1.5.1 pandas==1.0.5 scikit-learn==0.23.1 statsmodels==0.11.1

**Comment by gokceneraslan** [comment]
Output of the same code with scanpy 1.5.1:

![image](https://user-images.githubusercontent.com/1140359/88754404-8fd3a580-d12c-11ea-9ae6-866ab1da1255.png)

**Comment by gokceneraslan** [comment]
It'd be great have a test for this to catch such bugs next time, like checking the range of the scores.

**Comment by ivirshup** [comment]
My suspicion is that this is more likely to do with the plotting functions, than the calculation. I think the issue is that previously the axis limits weren't being set (though they were calculated). Now they are set, but it turns out they were calculated on the full range of scores – not just the plotted ones. Here's what a potential fix looks like:

<details>
<summary> Big images </summary>

Without fix:

![tmp](https://user-images.githubusercontent.com/8238804/88772041-7cbfe480-d1c3-11ea-80e9-9ea26c3d4cea.png)

With fix:

![tmp_new](https://user-images.githubusercontent.com/8238804/88772070-88aba680-d1c3-11ea-8872-16a26103b892.png)

</details>

What do you think? (ping @fidelram)

**Comment by Koncopd** [comment]
@ivirshup I think the problem happens because i removed the default top n filtering of genes in `rank_genes_groups`.

**Comment by ivirshup** [comment]
Ah, that makes sense. Either way, I don't think the intent of the function was to have the axis bounds determined by how many DE tests were saved.
