### ISSUE TITLE
Reproducibility of regress_out() results

### ISSUE THREAD

**Issue by marlena-D4C** [scverse/scanpy#1346]
Hi
I encountered a problem with **regress_out** function. The returned X matrix for the same input anndata varies for subsequent iterations. The function doesn't have any parameter such as "random_state" or "seed". Have you noticed this problem before? Is there a way to make this function more stable and return reproducibile results?
Thanks!

**Comment by ivirshup** [comment]
Thanks for the report! I believe the results should be the same for multiple runs.

Could you provide an example of this? I'm having a bit of trouble reproducing. Here's what I ran:

```python
import scanpy as sc
import numpy as np

pbmc = sc.datasets.pbmc68k_reduced()
a = pbmc.copy()
b = pbmc.copy()

sc.pp.regress_out(a, "phase")
sc.pp.regress_out(b, "phase")

assert np.array_equal(a.X, b.X)
assert not np.array_equal(a.X, pbmc.X)
```

Is this what you meant?

**Comment by eroell** [comment]
As we haven't heard back after the question we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
