### ISSUE TITLE
UMAP plotting can not properly colour np.nan values in categorical obs

### ISSUE THREAD

**Issue by Hrovatin** [scverse/scanpy#1355]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

Scanpy version: 1.5.1

If  np.nan values are present in obs column used for colouring `sc.pl.umap` they are coloured with the colour of the last non-nan category (see example below). This is very problematic as cells that are not annotated get the color of one of the categories.
This is another reason why https://github.com/theislab/scanpy/issues/1340 is needed - there should be a default for nan (such as gray).

I plotted an UMAP and coloured it by cell type (left). Then I replaced half of alpha cells' cell types (column pre_cell_type) with np.nan and plotted it again (right). Half of the alpha cells (previously coloured blue) are now coloured pink (colour of the last category, here named 'NA'). These cells should not be coloured pink - nan should have its own colour.

![slika](https://user-images.githubusercontent.com/47607471/89209123-fbe75b00-d5bd-11ea-9a46-6d3dd628cb31.png)

**Comment by ivirshup** [comment]
Thanks for all the great bug reports! This is really useful!

The way that we assign colors to each obs is basically:

```
values = adata.obs[categorical_column]
color_vector = np.asarray(adata.uns[color_key])[values.codes]
```

When there is a missing value in a categorical array, the code for that value is `-1` (which is why the color of the last category is being assigned). [Pandas does not allow you to make `NA` a category](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#missing-data), so `NA` will always have a code of `-1`

I think handling of this could take some consideration. I'm not sure we can safely set a default color for missing categorical values since that color (or one that looks very similar) could already be used. That said, it could be much more complex to allow passing a color for missing values. It might be worth looking into how other plotting libraries deal with missing categorical values and color. 

Right now we have a related concept with the `groups` argument. Any samples not in the passed groups will just be colored light gray. This could probably also handle missing values if we want to go with that. I've started an implementation of this in #1356.

**Comment by LuckyMD** [comment]
I think Seaborn would typically use `.dropna()` to just omit values that are `NA`, no? That would be safer than assigning a colour.

**Comment by Hrovatin** [comment]
I think it is important to see nan values (in my case above the whole pink NA cluster would not be seen if I had not changed np.nan to string 'NA'). Some plotting libraries (e.g. ComplexHeatmap in R) have a special parameter for missing values with some default.

**Comment by ivirshup** [comment]
I believe datashader uses a `clipping_colors ` parameter for this. Altair seems to add a category for null values, but this might not always be the case. Pandas [mostly drops nulls](https://pandas.pydata.org/docs/user_guide/visualization.html#plotting-with-missing-data).

**Comment by LuckyMD** [comment]
I guess this comes down to what you interpret an `NA` value as. If I want to show another category, I give it a name and it's shown. Doing this is very easy. If I don't assign a category to a group of observations, I would interpret this as this group of observations not being relevant in the context.

**Comment by ivirshup** [comment]
I think the result of a missing value should be very visible, whether through a warning or something in the plot. This comes from me thinking that I'd probably not intentionally have missing values most of the time, and really wouldn't want to miss that.

I generally go for having the points be light gray in the background when they aren't relevant.

**Comment by LuckyMD** [comment]
Then I guess light grays would need to be removed from the default colour maps? And the question remains for how to deal with this in a continuous covariate.

**Comment by flying-sheep** [comment]
Matplotlib’s color maps should be able to handle things, through [`ColorMap.set_bad`](https://matplotlib.org/api/_as_gen/matplotlib.colors.Colormap.html?highlight=set_bad#matplotlib.colors.Colormap.set_bad). We can do

```py
from copy import copy

def ...(...):
	...
	color_map = copy(color_map)
    color_map.set_bad('lightgray')
	...
    ax.scatter(..., cmap=color_map, plotnonfinite=True)
```

**Comment by ivirshup** [comment]
Currently matplotlibs colors maps are dealing with things, it's just their default "bad color" is often transparent. We currently don't do any handling of color maps, which makes dealing with continuous values a little more complicated.
