### ISSUE TITLE
Likely wrong % of cells in dotplot after pp.scale()

### ISSUE THREAD

**Issue by jcamunas** [scverse/scanpy#1361]
The function `sc.pl.dotplot()` can be used with processed data or raw data by setting `use_raw=True`. The % cells that express a gene is obtained by counting cells with expression above `expression_cutoff` (which by default is 0.0). 

However this is likely to produce a wrong result when using scaled and centered data (i.e. after `pp.scale()` ).  Unless I'm missing something, the percentage of cells expressing a gene should only be computed from raw data. 

Although this is the default usage of the dotplot function in scanpy notebooks, the default use in Seurat is the opposite, and it seems easy to use  `sc.pl.dotplot()` in scaled data without noticing this. Maybe a variable similar to `use_raw` to uncouple the use of raw data for the colormap and dotsize could solve this?

**Comment by ivirshup** [comment]
@fidelram, maybe you could comment on how this relates to your new work on the dotplots?

**Comment by fidelram** [comment]
In the described case, it is expected that `adata.raw` is set. Thus, by default `sc.pl.dotplot` will use the raw data instead of the scaled `adata.X`. In the case in which `adata.raw` is not set, then dotplot will wrongly compute the percentage.

The suggestion to uncouple the dot size and the dot color is very good and after the 1.6 relase of scanpy is now possible to do this using the `dot_color_df` (see https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.dotplot.html#scanpy.pl.dotplot). However, this requires that the user prepares a pandas dataframe for the color while the dot size (% of cells) can be computed based on raw, or a layer (depending on the settings for `use_raw` and `layer`). I am open to further suggestions.
