### ISSUE TITLE
Question on concatenation and memory use

### ISSUE THREAD

**Issue by ywen1407** [scverse/scanpy#1431]
I've been working on scRNA from different patients (diseased and healthy) control and was wondering what is the best approach to concatenate these data? It seems like inner join is usually recommended, but given significant individual variability (especially disease versus healthy states) there would be a large proportion of genes lost. Clustering also does not have good result. So I was wondering in this situation, shall I use outer join and fill value to zero? 

Another issue is memory use, I'm running this on google colab, and even using TPU, either using combat for batch correction after concatenation or concatetating two subsets of data after batch correction, would take much RAM that it just crashes (there're about 38K cells). Are there any way to limit memory use in this kind of situation? Thanks!

**Comment by LuckyMD** [comment]
Hey @ywen1407!

The ideal case is that you don't pre-filter the gene sets before concatenating. Then, if you have aligned both sets of samples to the same genome, everything should be fine and you can filter out genes afterwards. Otherwise an outer join would only assume all values you filtered out were 0, which is probably not the way forward. That's why the only decent option you really have is an inner join. I assume you should have the unfiltered objects somewhere though.

Regarding memory use: ComBat is something we (actually, this was thanks to @Marius1311) just re-implemented from python and R code that was flying around. We do not generally optimize methods that were published elsewhere. How much RAM are you using that it's crashing? I think Marius even made ComBat usable for sparse matrices, so it's already using less memory than it was before. 38K cells doesn't sound like something that would require more than 16GB RAM. I can run datsasets with 50k locally. You can of course always try other batch correction/data integration methods that are less memory intensive such as BBKNN or scVI. We tested scalability of data integration tools (also BBKNN and ComBat memory use) here: https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2. However, ComBat is one of the least memory intensive methods out there... so maybe there is little room for optimization here...

**Comment by Marius1311** [comment]
As long as my combat implementation handles sparse matrices correctly, a sparse 38k cell matrix should be absolutely no problem. Maybe check the implementation, it has been quite a while since I did this.

**Comment by ywen1407** [comment]
> Hey @ywen1407!
> 
> The ideal case is that you don't pre-filter the gene sets before concatenating. Then, if you have aligned both sets of samples to the same genome, everything should be fine and you can filter out genes afterwards. Otherwise an outer join would only assume all values you filtered out were 0, which is probably not the way forward. That's why the only decent option you really have is an inner join. I assume you should have the unfiltered objects somewhere though.
> 
> Regarding memory use: ComBat is something we (actually, this was thanks to @Marius1311) just re-implemented from python and R code that was flying around. We do not generally optimize methods that were published elsewhere. How much RAM are you using that it's crashing? I think Marius even made ComBat usable for sparse matrices, so it's already using less memory than it was before. 38K cells doesn't sound like something that would require more than 16GB RAM. I can run datsasets with 50k locally. You can of course always try other batch correction/data integration methods that are less memory intensive such as BBKNN or scVI. We tested scalability of data integration tools (also BBKNN and ComBat memory use) here: https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2. However, ComBat is one of the least memory intensive methods out there... so maybe there is little room for optimization here...

Thanks for your suggestion! Let's say that 8 diseased patients have gene A expressed at different level, but other 3 diseased patients don't, and the other healthy controls dont have this gene expressed either. After inner join, wouldn't this gene be lost?

**Comment by ywen1407** [comment]
> Hey @ywen1407!
> 
> The ideal case is that you don't pre-filter the gene sets before concatenating. Then, if you have aligned both sets of samples to the same genome, everything should be fine and you can filter out genes afterwards. Otherwise an outer join would only assume all values you filtered out were 0, which is probably not the way forward. That's why the only decent option you really have is an inner join. I assume you should have the unfiltered objects somewhere though.
> 
> Regarding memory use: ComBat is something we (actually, this was thanks to @Marius1311) just re-implemented from python and R code that was flying around. We do not generally optimize methods that were published elsewhere. How much RAM are you using that it's crashing? I think Marius even made ComBat usable for sparse matrices, so it's already using less memory than it was before. 38K cells doesn't sound like something that would require more than 16GB RAM. I can run datsasets with 50k locally. You can of course always try other batch correction/data integration methods that are less memory intensive such as BBKNN or scVI. We tested scalability of data integration tools (also BBKNN and ComBat memory use) here: https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2. However, ComBat is one of the least memory intensive methods out there... so maybe there is little room for optimization here...

Thanks for the explanation. I tried concatenating all samples with inner join and it actually went well! The overall number of genes do drop from 45K to around 20K but after preprosessing, the clustering looks OK.

**Comment by LuckyMD** [comment]
I guess 20k genes is still quite a lot. After filtering out genes that aren't expressed in most cells i typically have between 12k and 18k genes left.
