### ISSUE TITLE
How to get Louvain clustering labels from adata/scanpy

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#144]
I am trying to get clustering labels from Louvain. I followed the Seurat-like notebook (https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb).

I am able to run the clustering and visualize it on tSNE, with:

```python
>>> sc.tl.louvain(adata)
running Louvain clustering
    using the "louvain" package of Traag (2017)
    finished (0:00:00.11) --> found 8 clusters and added
    'louvain', the cluster labels (adata.obs, categorical)
>>> sc.pl.tsne(adata, color='louvain')
```

However, I cannot find the clustering labels under adata:

```
AnnData object with n_obs × n_vars = 1320 × 5014 
    uns: 'pca'
    obsm: 'X_pca', 'X_tsne'
    varm: 'PCs'
```

I tried looking directly into obs, obsm etc., but I didn't find any label. But the plots work out correctly. How is it possible?

I have the default louvain parameters, so it should be updated in-place.

**Comment by fbrundu** [comment]
Now it's working:

```
AnnData object with n_obs × n_vars = 1320 × 5014 
    obs: 'louvain'
    uns: 'pca', 'neighbors', 'louvain'
    obsm: 'X_pca', 'X_tsne'
    varm: 'PCs'
```

I don't know what happened and I to reproduce it.

**Comment by falexwolf** [comment]
Hm, very strange... Did you copy your AnnData somewhere on the way between? Also, when subsetting, internally a view of AnnData is generated. This view listens to whether you want to add an additional annotation to the object... if you do so, a copy is made and the view becomes an actual object in memory... All this happens automatically and you do not need to worry about it as a user... I have not encountered any problem with it, except when you want to change the data matrix of the view... this will be resolved soon. Could it be that something like this happened? Otherwise, no one reported that issue.

**Comment by fbrundu** [comment]
I am unsure about it, I will take a look if this issue happens again. Thanks.
