### ISSUE TITLE
sc.pl.umap error message if sc.tl.umap has not been computed.

### ISSUE THREAD

**Issue by alejandro-jimenezsanchez** [scverse/scanpy#1460]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
Hi scanpy develovepers,

A rotation student asked me what is `sc.pl.umap` showing if `sc.tl.umap` was not computed beforehand. To which I don't have the answer since I have never done it.

If you know the answer I'd like to know it, but most importantly, I think it would be nice to have an error message in the UMAP plotting function if UMAP has not been computed. Unless there were meaning and a reason to use `sc.pl.umap` without running `sc.tl.umap` previously, and it was designed that way purposely. I assume this would apply to other plotting functions too.

Thanks!
Alejandro

**Comment by cdedonno** [comment]
Hi @SNRNS, 

`sc.pl.umap` looks for the UMAP coordinates that should be stored in `adata.obsm`, specifically it looks for coordinates in `adata.obsm['X_umap']`. These coordinates are computed and stored by `sc.tl.umap`. If `adata.obsm['X_umap']` does not exist the plotting function does return an error which I think is pretty self-explanatory:

`KeyError: "Could not find entry in 'obsm' for 'umap'.\nAvailable keys are: ['X_pca']."`

It must be that you have some coordinates already stored in `adata.obsm['X_umap']`, this could happen because you have subset the current adata from a bigger one, for which you had computed the UMAP, or maybe you got the data already preprocessed.

**Comment by cdedonno** [comment]
@SNRNS I will close this issue for now. Feel free to open again or make further inquiries if you still have doubts.
