### ISSUE TITLE
CITE-seq data  normalization

### ISSUE THREAD

**Issue by massonix** [scverse/scanpy#1469]
Dear scanpy team,

In your CITE-seq  vignette you use the function `sc.pp.normalize_geometric(protein)` to normalize CITE-seq data. However, I think the description and motivation for the method are not detailed enogh to understand what is going on under the hood. Could you please give me a brief explanation on how that works? I've been using the centered log-ratio in Seurat, but there is definetely room for improvement.

Thanks a lot for you time and help!

**Comment by ivirshup** [comment]
It's equivalent to the CLR transform.

However, I'm not sure if this is the right way to go. CLR was used in a formative paper on the topic (doi:10.1038/nmeth.4380), and it's been brought forward from there. Here's that explanation for it's use:

<img width="559" alt="CBMC antibody-derived tag normalization and clustering. Since each ADT count for a given cell can be interpreted as part of a whole (all ADT counts assigned to that cell), and there are only 13 components in this experiment, we treated this data type as compositional data and applied the centered log ratio (CLR) transformation" src="https://user-images.githubusercontent.com/8238804/98912624-75c2a500-251a-11eb-92e0-6d1d9004e3e2.png">

I'm not convinced the UMIs from antibodies are more compositional than UMIs from mRNA, especially considering they are captured and amplified together.

**Comment by adamgayoso** [comment]
I'm also a bit confused about how the CLR is applied. In the CITE-seq paper, I think it was done within a cell (over proteins), then I think they had switched to within a protein (over cells), and now in Seurat v4 it appears to be back to within a cell.

Any per cell normalization is a bit tricky because the panels will differ between datasets as well as the titration of antibodies used. The simplest thing to me seems to be a simple log transformation combined with per protein scaling, as values between proteins are not comparable to begin with.

We have some additional thoughts in the appendix of our totalVI paper.

**Comment by Zethson** [comment]
CLR is implemented in Muon which we recommend for people interested in CITE-seq data: https://muon.readthedocs.io/en/latest/omics/citeseq.html#clr

**Comment by shihsama** [comment]
Hi@Zethson,
    Thanks for your link! I got another question. Followed by CLR, should we perform pp.log1p() as we do in scRNA-seq pipline?
    Looking forward to your kind advice ~
