### ISSUE TITLE
PR problem: docstring error

### ISSUE THREAD

**Issue by pinin4fjords** [scverse/scanpy#1484]
Hi!

I'm having trouble getting the CI to pass on this PR: https://github.com/theislab/scanpy/pull/1476

This seems to be the issue:

```
>           raise SyntaxError(msg, (filename, lineno, 2, text))
E             File "/home/travis/build/theislab/scanpy/scanpy/external/pp/_scrublet.py", line 9
E               >   <
E                ^
E           SyntaxError: Header of function `scanpy.external.pp._scrublet.scrub_doublets`’s docstring should start with one-line description:
E           
E           ␣␣␣␣"""\
E           ␣␣␣␣My one-line␣description.
E           
E           ␣␣␣␣…
E           ␣␣␣␣"""
scanpy/tests/test_docs.py:38: SyntaxError
```

... but the function does have that one-line description. 

Would you be able to suggest to me what I'm doing wrong?

**Comment by giovp** [comment]
mmh, I checked the PR, could it be that for some args in the docs you have the colon and typing? Can you try to remove all of them and check again?

**Comment by ivirshup** [comment]
The issue is that there was a blank line starting with three spaces, and that triggered an error whose message wasn't particularly related to that. I think this test could probably get rewritten.

https://github.com/theislab/scanpy/blob/a8ee1e01e6cea1d3b9f5474997508c99497d4fb4/scanpy/tests/test_docs.py#L18-L38

The error came from the `if any(broken)` block. Basically it's checking for lines which aren't 1) empty, 2) start with a four space indent. The error message is specific to the first line. The PR had a three line indent in between paragraphs triggering the failure.

@flying-sheep, thoughts on removing this part of the test? Should we have a separate rst linting check?

**Comment by flying-sheep** [comment]
If a linter flexible enough to enforce this existed, it would be great.

The test should definitely exist, something in our code requires the docstrings to have that format, I just forgot which part. (But in any case it guarantees consistent formatting so that’s nice)

#1492 should fix that test to ignore blank lines for the time being.

Also isn’t it cool that it points exactly to the problematic line?
