### ISSUE TITLE
continuous color map

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#1550]
Hi,
When plotting gene expression profile on tsne/umap, Cellranger and Seurat can display the zero-expression cells in gray color, while scanpy doesn't display those cells. such as:
Seurat featureplot:
![image](https://user-images.githubusercontent.com/29703450/102605221-f1d68b00-415f-11eb-9bc2-797a25db897e.png)
  
And cellranger:
![image](https://user-images.githubusercontent.com/29703450/102605354-1df20c00-4160-11eb-9a16-501da6d951d4.png)

It's useful to show all cells (including zero-expression cells), because we can estimate the percentage of cells that expressing some markers at a glance. It seems that all cells are in gray color, then red/blue color are overlaid on the bottom color (namely the gray color) according to the gene expression value . In addition to Scanpy, cellranger and seurat are also very popular, many students ask me to adopt this style on their plot, because they read some papers and see this style on the papers, then they were influenced a lot by cellranger and seurat. I don't know how to fulfill it with scany. I cannot find the corresponding colormap in scanpy and matplotlib, Is there a way to add this feature ?

**Comment by wangjiawen2013** [comment]
Scanpy has enhanced sc.pl.umap function last year. For example, now sc.pl.umap(adata,color=["louvain"],groups="1") can highligt cluster 1 while displaying other clusters in gray color. I think they are very similar, excepting that  gene expressing values are continuous variables.

**Comment by ivirshup** [comment]
What you mean by not showing the cells? Do you have an example of this? For sure some color maps (like `"Reds"`) can seem to make cells seem invisible since white is their lowest value, but I'm not aware of any cell hiding.

As for displaying zero count cells as some color, you can do that by passing a `cmap`, e.g. a cubehelix one:

```python
import seaborn as sns
import scanpy as sc

pbmc = sc.datasets.pbmc3k_processed().raw.to_adata()

sc.pl.umap(
    pbmc,
    color="LGALS2",
    cmap=sns.cubehelix_palette(dark=0, light=.9, as_cmap=True)
)
```

![image](https://user-images.githubusercontent.com/8238804/102610132-c6b06380-4180-11eb-8da1-6edb2a9feed0.png)


Or you could generate your own colormap where you can choose the color for a low value:

```python
sc.pl.umap(
    pbmc,
    color="LGALS2",
    # Felt appropriate for the data
    cmap=sns.blend_palette(["lightgray", sns.xkcd_rgb["blood"]], as_cmap=True)
)
```

![image](https://user-images.githubusercontent.com/8238804/102610181-dcbe2400-4180-11eb-806b-713a844fdf07.png)

You can also get a bit more involved and set low values to be shown as a specific color (thought this is both a bit inelegant, and has a dramatic cutoff):

```python
import matplotlib as mpl
from copy import copy

reds = copy(mpl.cm.Reds)
reds.set_under("lightgray")
sc.pl.umap(pbmc, color="LGALS2", cmap=reds, vmin=0.00001)
```

![image](https://user-images.githubusercontent.com/8238804/102610145-cca64480-4180-11eb-9517-aadb4b80cc94.png)

**Comment by wangjiawen2013** [comment]
Thanks for you detailed guidance. All I want is to display zero count cells as some color (gray) and this is what cellranger and seurat do. I can do it now following the above code. This is just what I want !

**Comment by ivirshup** [comment]
Glad to help!
