### ISSUE TITLE
Show example plots as part of documentation

### ISSUE THREAD

**Issue by fidelram** [scverse/scanpy#1604]
In seaborn, the docstring example plots are shown as part of the documentation. Would be great to have this as part of scanpy as this will motivate the creation of more examples as part of the docstring while keeping them up-to-date. 

See for example: https://seaborn.pydata.org/generated/seaborn.catplot.html
![image](https://user-images.githubusercontent.com/4964309/105457501-3a192980-5c87-11eb-8a17-050b0dc5b67b.png)

Does anyone has experience on how to achieve this?

**Comment by giovp** [comment]
@fidelram that's a really great point and something I'd like to discuss at next meeting (already put it in the agenda).

Another great example of such examples 😅 is the way @michalk8 set it up for [cellrank](https://cellrank.readthedocs.io/en/latest/auto_examples/index.html) and squidpy [not yet public].
The even nicer thing is that @michalk8 implemented a CI pipeline for the tutorials/examples part of the repo so that every time there is a change in master of the original repo, the examples are refreshed in the notebooks repo, so to have them always up to date.

Would be really cool to concentrate efforts and try to get this logic also in scanpy (makes it both very user friendly and robust from a maintainer perspective)

**Comment by ivirshup** [comment]
I would love to have this! I've been talking about this with @falexwolf and a bit with @flying-sheep.

Seaborn uses a sphinx extension from `matplotlib` to generate the plots ([plot directive](https://matplotlib.org/3.1.3/devel/plot_directive.html)).

I would definitely like to get tutorials running on CI as well, but think this is a little separate (some previous discussion: #302).

1. Tutorials can use a lot more computational resources than plotting.
2. These examples are written in the docstrings, while tutorials are currently in notebooks. It'll probably be a different set of tools to render these.

**Comment by fidelram** [comment]
I tried the sphinx extension but could not get any result. Can somebody take over this?

**Comment by ivirshup** [comment]
Closed, as the initial issue is done, and being tracked elsewhere.
