### ISSUE TITLE
Problems with Drosophila genome due to gene called nan

### ISSUE THREAD

**Issue by Knievl** [scverse/scanpy#1708]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

To do some trajectory analysis, I wanted to first try some tutorials to adapt to the workflow of scanpy, after calling sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True) i got the valueerror below. I also tried different Drosophila Datasets and it always happens, and its due to a gene called "nan" in the features.tsv or genes.tsv, if this gene is renamed, scanpy works as intended.

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-455e630e3278> in <module>
      1 adata.var['mt'] = adata.var_names.str.startswith('mt:')  # annotate the group of mitochondrial genes as 'mt'
----> 2 sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\preprocessing\_qc.py in calculate_qc_metrics(adata, expr_type, var_type, qc_vars, percent_top, layer, use_raw, inplace, log1p, parallel)
    286         X.eliminate_zeros()
    287 
--> 288     obs_metrics = describe_obs(
    289         adata,
    290         expr_type=expr_type,

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\preprocessing\_qc.py in describe_obs(adata, expr_type, var_type, qc_vars, percent_top, layer, use_raw, log1p, inplace, X, parallel)
    119     for qc_var in qc_vars:
    120         obs_metrics[f"total_{expr_type}_{qc_var}"] = (
--> 121             X[:, adata.var[qc_var].values].sum(axis=1)
    122         )
    123         if log1p:

C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\_index.py in __getitem__(self, key)
     49                 return self._get_sliceXslice(row, col)
     50             elif col.ndim == 1:
---> 51                 return self._get_sliceXarray(row, col)
     52             raise IndexError('index results in >2 dimensions')
     53         elif row.ndim == 1:

C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\csr.py in _get_sliceXarray(self, row, col)
    321 
    322     def _get_sliceXarray(self, row, col):
--> 323         return self._major_slice(row)._minor_index_fancy(col)
    324 
    325     def _get_arrayXint(self, row, col):

C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\compressed.py in _minor_index_fancy(self, idx)
    737         """
    738         idx_dtype = self.indices.dtype
--> 739         idx = np.asarray(idx, dtype=idx_dtype).ravel()
    740 
    741         M, N = self._swap(self.shape)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_asarray.py in asarray(a, dtype, order, like)
    100         return _asarray_with_like(a, dtype=dtype, order=order, like=like)
    101 
--> 102     return array(a, dtype, copy=False, order=order)
    103 
    104 

ValueError: cannot convert float NaN to integer
```

#### Versions

<details>

scanpy==1.7.1 anndata==0.7.5 umap==0.5.1 numpy==1.20.1 scipy==1.6.1 pandas==1.1.3 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.9.0 leidenalg==0.8.3

</details>

**Comment by ivirshup** [comment]
You can control which values `pandas.read_csv` reads in as `NaN` from text files with the arguments `na_filter`, `keep_default_na`, and `na_values`.

**Comment by liliay** [comment]
HI @Knievl I am having the exact same issue, on Drosophila datasets, did you solve this issue ? 
For now i've tried to replace nan values with arbitrary indexes and still had the same issue. 
Then, I decided to see what happens when i drop the problematic NaN rows in df.var and cols in df.X, but it is very tricky to change anything in the nparray df.X (seems impossible from what i read on forums).
I would really like to now how you solved this 

Lilia

**Comment by Knievl** [comment]
Hi  @liliay,

for me the problem was as i wrote, that in my features.tsv or genes.tsv files one gene was named nan and i just renamed it with an editor to nanchung and afterwards analyzing scrnaseq files was no problem anymore. So i think we have a different problem here.

**Comment by liliay** [comment]
Thank you @Knievl ! Had the exact same problem ! 
Changing the gene name in the features.tsv files helped solve this issue.

**Comment by Affogat0** [comment]
I ran into #1259 recently and dug into it. I wanted to check whether a fix here is still wanted, since this was originally closed as Upstream.

New evidence on current `main`:
- The original `calculate_qc_metrics` exception no longer reproduces (unrelated changes altered how `var_names` are cast).
- The root cause you flagged is still present: `read_10x_mtx()` reads `features.tsv` via `pd.read_csv()` without `keep_default_na=False`, so a gene symbol like `"nan"` still gets parsed as a missing value, not a string.
- With pandas 3.0, that missing value remains missing in `adata.var_names`, so the original identifier is silently lost. String based operations on `var_names` then treat that entry as missing rather than as the gene symbol `"nan"`.
- Scanpy already guards against a related class of this problem (numeric gene IDs getting misinterpreted), so a similar targeted fix for NA-like string identifiers would be consistent with that precedent.

I'd be happy to submit a small PR using `keep_default_na=False` (or whatever approach you prefer) along with a regression test asserting that NA-like gene symbols are preserved unchanged.
