### ISSUE TITLE
Scanpy docs are down?

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#1746]
Getting this across multiple browsers.

![Screen Shot 2021-03-16 at 9 27 49 AM](https://user-images.githubusercontent.com/10859440/111344731-e1885c00-8639-11eb-8cb0-93fd463844c4.png)

**Comment by gokceneraslan** [comment]
Is it normal that https://scanpy.readthedocs.io/en/stable/ works just fine but https://scanpy.readthedocs.io redirects to the hosted readthedocs and eventually fails?

**Comment by adamgayoso** [comment]
Weird, I guess I usually use the latter, which now fails (but didn't previously). First link works.

**Comment by ivirshup** [comment]
I can't tell if this is an issue with `readthedocs` or hosted redirects. I'm also not sure why we have hosted readthedocs since we pay for readthedocs hosting.

I assume this is related to `Custom Domains` in the `readthedocs` settings:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/8238804/111412288-41f9c500-8730-11eb-99a6-775ca23d9a3e.png">

But I get a fail whale if I try to edit that:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/8238804/111412338-58a01c00-8730-11eb-964b-d13743e7fbfe.png">

Any suggestions @falexwolf @flying-sheep?

**Comment by ivirshup** [comment]
Fixed, we've got a bit of custom plan with readthedocs and an update to their billing code broke that url.
