### ISSUE TITLE
cluster heatmap

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#178]
In scanpy, clustermap uses all the clusters and genes by default to plot the heatmap, however, it is more flexible if users can use a certain clusters and marker genes they are interested in. Can scanpy perform this function, or anyone who can add some extensions to scanpy to achieve this goal?

**Comment by fidelram** [comment]
Can you see if PR #175 is what you are looking for?

**Comment by wangjiawen2013** [comment]
Great, it is. what if I want to add multiple obs_keys (such as lovain, cell_type et al.,), and, when will the new version scanpy be released?

**Comment by fidelram** [comment]
I thought about adding that functionality. Probably is useful when the
second obs_key has few categories because the second category subdivides
the first category. A quick hack is to add a new observation that is the
combination of the first and second keys. Eg. For 4 clusters, and 2 cell
types, the new observation would be cluster_1_cell_type_1,
cluster_1_cell_type_2, cluster_2_cell_type_1 etc.

**Comment by falexwolf** [comment]
Yes, we should definitely have the possibility of visualizing several observation annotations in the future. But Fidel's function is a very good start.

I can release a new subversion of Scanpy anytime if you need it.
