### ISSUE TITLE
No negative logFC values after running scanpy.tl.rank_genes_groups()

### ISSUE THREAD

**Issue by aditisk** [scverse/scanpy#1800]
Hello,

I'm using the Wilcoxon method from the scanpy.tl.rank_genes_groups() function for my dataset. I am not seeing any logFC values in the output (the lowest logFC is zero). Should I be expecting to see some negative values (like we see in bulk RNAseq DE results) ?

I apologize in advance if this is a naive question. Thanks for your help.

**Comment by ivirshup** [comment]
Yes, you should probably see negative log fold changes, but they would be in the lower ranked genes (since we sort by test statistic).

For example:

```python
pbmc = sc.datasets.pbmc3k_processed().raw.to_adata()
sc.tl.rank_genes_groups(pbmc, 'louvain', method='wilcoxon')
print(sc.get.rank_genes_groups_df(pbmc, "B cells").tail().to_markdown())
```

|       | names   |   scores |   logfoldchanges |        pvals |   pvals_adj |
|------:|:--------|---------:|-----------------:|-------------:|------------:|
| 13709 | IL32    | -16.6762 |         -4.0097  | 1.95318e-62  | 1.4881e-59  |
| 13710 | ANXA1   | -17.0521 |         -3.27545 | 3.37183e-65  | 2.72007e-62 |
| 13711 | S100A6  | -19.6524 |         -2.86864 | 5.51413e-86  | 5.40148e-83 |
| 13712 | TMSB4X  | -21.137  |         -1.17325 | 3.63515e-99  | 3.8348e-96  |
| 13713 | S100A4  | -22.1246 |         -3.50364 | 1.83143e-108 | 2.7907e-105 |

**Comment by aditisk** [comment]
Hi @ivirshup, thanks for this snippet of code, I can now find the negative values at the bottom of the list.
