### ISSUE TITLE
how to select cells manually in scanpy?

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1992]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...

I want to save h5ad object without cells in the red circle, how to do that in scanpy?

Thank you
![image](https://user-images.githubusercontent.com/23288387/132060260-4700d085-595e-473f-ab09-6ff70ffde357.png)

**Comment by Koncopd** [comment]
Do you have any criteria to select these cells other than the plot?

**Comment by FADHLyemen** [comment]
No, I need to delete these scattered cells

**Comment by eroell** [comment]
Just came across this - is this still relevant?
Scanpy as is does not feature a neat solution integrating with interactive interfaces which would allow to manually tag/select individual points from a plot - for such tasks, [holoviz](https://holoviz.org/) tools might be considered.
As sidenote, a heads-up about considering 2D representations with caution e.g. [here](https://www.sciencedirect.com/science/article/pii/S2405471223002090?via%3Dihub) - considering metrics instead of visual low-dimensional representations to detect or remove outliers might be considered as a viable alternative here in many cases :)
