### ISSUE TITLE
Which data should be used for finding marker genes?

### ISSUE THREAD

**Issue by hyjforesight** [scverse/scanpy#2029]
Hello all,
In the “Finding marker genes” part of PBMC3K tutorial, the authors mentioned that “For this, by default, the .raw attribute of AnnData is used in case it has been initialized before” and the fuction `sc.tl.rank_genes_groups(adata, ‘leiden’, method=‘t-test’)` setting `use_raw=True` as default.
I tried `use_raw=False` in this `sc.tl.rank_genes_groups()` function and found that the results of marker genes are quite different. So, which data is recommended for finding the marker genes, adata after scaling, which is `use_raw=False`, or `adata.raw`?
Thanks!
Best
YJ

**Comment by hyjforesight** [comment]
use_raw=False always create errors.

**Comment by Zethson** [comment]
I'd recommend that you read @LuckyMD paper: https://www.embopress.org/doi/full/10.15252/msb.20188746
This question is answered in the paper.

**Comment by hyjforesight** [comment]
Hello @Zethson 
Thanks for the response.
I read the paper. I understand that using the raw data to calculate the maker genes of clusters is an appropriate way, but the raw data was not regressed out with mitochondrial genes, gene counts, cell cycle scores...So there will be so many mito genes ranked on the top of the marker gene list. What shall we do with these mito genes?

In Seurat, they did every downstream analysis and plotting by using the log-transformed and scaled data (see below, the scaled dots in Seurat violin plot). Scanpy draws all plots by setting `use_raw=True`. I'm wondering which method is better?
![image](https://user-images.githubusercontent.com/75048821/149460182-c5c11295-ca78-4bfe-aa8b-d13bade4b21f.png)

Thanks!
Best,
YJ

**Comment by LuckyMD** [comment]
Hi @hyjforesight!

As mentioned in the paper, plotting corrected data is definitely the way forward. I'm not sure about regressing out all of these biological covariates (like regressing out MT fraction). In general, it can be quite informative to find that you have different MT gene expression between clusters. This can highlight different respiratory (and maybe metabolic) activity as well as data quality differences. Otherwise, feel free to just ignore the MT genes by masking them from the analysis.
