### ISSUE TITLE
UMAP goes wrong on scanpy v1.8.2

### ISSUE THREAD

**Issue by buesra-oezmen** [scverse/scanpy#2148]
- [y] I have checked that this issue has not already been reported.
- [y] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
Hello,

I am using scanpy version 1.8.2 and the umap shows clusters like this

<img width="423" alt="Bildschirmfoto 2022-02-21 um 11 39 42" src="https://user-images.githubusercontent.com/59925710/154984424-6b54082b-b680-42af-b00b-9d931efcfbac.png">

But the clusters should have more distance from each other.
Do you have an idea how to solve this issue?

Many thanks for your help!
Büsra

### Minimal code sample

```python
import scanpy as sc

adata_mvi.obsm["MultiVI_latent"] = mvi.get_latent_representation()
sc.pp.neighbors(adata_mvi, use_rep="MultiVI_latent")
sc.tl.umap(adata_mvi)   
sc.tl.leiden(adata_mvi)
sc.pl.umap(adata_mvi, color='leiden')      
```

#### Versions

<details>

anndata     0.7.8
scanpy      1.8.2
sinfo       0.3.4

</details>

**Comment by LuckyMD** [comment]
Hey @buesra-oezmen! I don't think this is a UMAP issue, but instead an issue of the MultiVI parameterization or the data. But as I know the data quite well in this case, I'm pretty sure it's maybe just a MultiVI model that is not sufficiently trained. Maybe try for a few more epochs? Or otherwise maybe the network architecture needs to be adapted.
