### ISSUE TITLE
Error with scanpy.api.pl.highest_expr_genes()

### ISSUE THREAD

**Issue by pritykin** [scverse/scanpy#220]
I have an error when trying this function for my data:

```
sc.pl.highest_expr_genes(adata)
```
results in

```
filtered out 14139 cells that have less than 1 counts
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-1f5b130b9d4e> in <module>()
----> 1 sc.pl.highest_expr_genes(adata)

/usr/local/lib/python3.6/site-packages/scanpy-1.2.2+90.g47c579f-py3.6.egg/scanpy/plotting/qc.py in highest_expr_genes(adata, n_top, save, show, ax, **kwargs)
     41 
     42     # identify the genes with the highest mean
---> 43     dat.var['mean_percent'] = dat.X.mean(axis=0).A1
     44 
     45     top = dat.var.sort_values('mean_percent', ascending=False).index[:n_top]

AttributeError: 'numpy.ndarray' object has no attribute 'A1'
```

It is not critical, but I wonder why this error happens. I have the most recent version from github. Maybe I'm not transforming my data to a certain format properly? Didn't find this documented anyway. However, a lot of other analysis that I do via Scanpy works for me, so generally the data is read and processed correctly.

**Comment by LuckyMD** [comment]
This sounds like it may have to do with the matrix format of `adata.X`. Could you check the type of your adata.X object?

**Comment by pritykin** [comment]
It's numpy.ndarray:
```type(adata.X)```
``` numpy.ndarray```
I guess it should be matrix? It's loaded once like this 
```
path = '../count-genes/datafiles/all_counts.csv'
adata = sc.read(path, cache=True)
```
and then always manipulated with anndata interface. Maybe it should be transformed right after loading?

**Comment by LuckyMD** [comment]
From your side everything seems okay. `numpy.ndarray` is the expected dense matrix format. It seems the function was written for sparse matrices. I'll see if I can tweak it.

**Comment by LuckyMD** [comment]
It should be fixed now. If you pull the latest version from github you can check. Please let me know if there's still an issue.

**Comment by falexwolf** [comment]
Thank you, @LuckyMD!

**Comment by pritykin** [comment]
Works for me now, thank you!

**Comment by Nishant-Gupta-17** [comment]
> From your side everything seems okay. `numpy.ndarray` is the expected dense matrix format. It seems the function was written for sparse matrices. I'll see if I can tweak it.

Hello @LuckyMD , I am facing problem with `sc.pl.highest_expr_genes(adata_orig, n_top=20)` as well. Attaching some details:
I started by reading in the file as:

`adata_orig = sc.read_h5ad('covid_portal_210320_with_raw.h5ad', backed = 'r')`

After printing the `adata_orig` object, i get the following output:

```
AnnData object with n_obs × n_vars = 647366 × 24929 backed at 'covid_portal_210320_with_raw.h5ad'
    obs: 'sample_id', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'full_clustering', 'initial_clustering', 'Resample', 'Collection_Day', 'Sex', 'Age_interval', 'Swab_result', 'Status', 'Smoker', 'Status_on_day_collection', 'Status_on_day_collection_summary', 'Days_from_onset', 'Site', 'time_after_LPS', 'Worst_Clinical_Status', 'Outcome', 'patient_id'
    var: 'feature_types'
    uns: 'hvg', 'leiden', 'neighbors', 'pca', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    layers: 'raw'
```

After this, when I tried running the command:
`sc.pl.highest_expr_genes(adata_orig, n_top=20, )`

I get the following output:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-c4ab6dadfa42> in <module>
----> 1 sc.pl.highest_expr_genes(adata_orig )

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\plotting\_qc.py in highest_expr_genes(adata, n_top, show, save, ax, gene_symbols, log, **kwds)
     65 
     66     # compute the percentage of each gene per cell
---> 67     norm_dict = normalize_total(adata, target_sum=100, inplace=False)
     68 
     69     # identify the genes with the highest mean

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\preprocessing\_normalization.py in normalize_total(adata, target_sum, exclude_highly_expressed, max_fraction, key_added, layer, layers, layer_norm, inplace, copy)
    174         counts_per_cell = X[:, gene_subset].sum(1)
    175     else:
--> 176         counts_per_cell = X.sum(1)
    177     start = logg.info(msg)
    178     counts_per_cell = np.ravel(counts_per_cell)

AttributeError: 'SparseDataset' object has no attribute 'sum'
```
And when I run the command:
`type(adata_orig.X)`
I get the output as:
`anndata._core.sparse_dataset.SparseDataset`

After reading your comment, I feel that earlier the scanpy module was expecting the sparse dataset as the input, but you have changed it to expect the dense format , and maybe that's the reason for this error? I am just two days into the world of scanpy and any help would be highly appreciated, in order to make this error go away.

Also, to help you in debugging, I'd like to mention that the raw data in this dataset is present in the layer, which has the name 'raw' and the adata_orig.raw is set to null as of now. and when i try to run : `adata_orig.layers['raw'].sum(1)` it runs with no error. While running: `adata_orig.X.sum(1)` gives me the error as : 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-951a31c71c45> in <module>
----> 1 adata_orig.X.sum(1)

AttributeError: 'SparseDataset' object has no attribute 'sum'
```

PS: I downloaded this` .h5ad` file from a published research paper to perform some analysis over it, would be happy to provide you the link to same if required.
