### ISSUE TITLE
Issue about plot stackedviolin.

### ISSUE THREAD

**Issue by UboCA** [scverse/scanpy#2298]
- [√ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ √] Other?

Hi, when I used stacked violin to plot gene expression among groups on UMI levels, I was confused about the color bar about it. 
In detail you can see the following picture I got.

![image](https://user-images.githubusercontent.com/69028068/180611435-9b60e159-082e-4643-9b6e-d188f1e9261b.png)

Like legend description 'Median expression in group', I guess the color palette is related about umi count value after scaling them among different groups (X-axis)? I'm not sure about the meaning of the color map.

Similar to Seurat displaying way like 
![image](https://user-images.githubusercontent.com/69028068/180611917-6d61c715-8aee-4843-9f09-d11c8400cee6.png)

How can I get similar plot by sc.pl.stacked_violin,  and plot umi distribution only, without color map?

Any direction would be appreciated, thanks :)

**Comment by XiangyangWang296** [comment]
Is it useful to change parameter including 'standard_scale'  or norm?

**Comment by LisaSikkema** [comment]
Hi @UboCA,

You can use the  `row_palette` argument for this, as in this example:
```python
import scanpy as sc
adata = sc.datasets.pbmc3k_processed()
sc.pl.stacked_violin(
    adata,
    var_names=["PTPRC", "RER1"],
    groupby="louvain",
    row_palette="tab10",
    # swap_axes=True,
)
```
Which gives:
<img width="227" alt="Screenshot 2022-09-24 at 17 43 01" src="https://user-images.githubusercontent.com/32548783/192106800-8e17fee3-ba70-4727-8af7-67aa74472cf0.png">

If you want to color by gene instead of by group, you can use the swap_axes argument.

**Comment by UboCA** [comment]
Got it, many thanks!

**Comment by RRRReyes** [comment]
> Hi @UboCA,
> 
> You can use the `row_palette` argument for this, as in this example:
> 
> ```python
> import scanpy as sc
> adata = sc.datasets.pbmc3k_processed()
> sc.pl.stacked_violin(
>     adata,
>     var_names=["PTPRC", "RER1"],
>     groupby="louvain",
>     row_palette="tab10",
>     # swap_axes=True,
> )
> ```
> 
> Which gives: <img alt="Screenshot 2022-09-24 at 17 43 01" width="227" src="https://user-images.githubusercontent.com/32548783/192106800-8e17fee3-ba70-4727-8af7-67aa74472cf0.png">
> 
> If you want to color by gene instead of by group, you can use the swap_axes argument.

Hi, 

I solved the issue of inputting specific colors with the row_palette argument, but when using swap_axes to have the same plot as in Seurat (bottom image), it colors genes instead clusters as you mention. Is there any way to input the palette list by columns instead of by rows? 

![image](https://github.com/scverse/scanpy/assets/94078098/71771dfd-8927-442b-93cf-d2ff85a6187e)
