### ISSUE TITLE
deprecate/remove read spatial and plotting spatial from scanpy.

### ISSUE THREAD

**Issue by giovp** [scverse/scanpy#2331]
I think it makes sense to deprecate and then remove `sc.read_visium`. and `sc.pl.spatial` since I don't plan to maintain it here anymore and updated versions are present in Squidpy. What do you think @ivirshup ?

**Comment by Zethson** [comment]
I would like to second this. I think that it makes sense that we don't duplicate functionality and responsibility of our core tools. People shouldn't be looking for spatial stuff in scanpy nor be confused if they suddenly see spatial tooling in the scanpy docs. We should always point them to the awesome squidpy.

**Comment by linhuawang** [comment]
I just had issues using `sc.pl.spatial` after reading spaceranger2.0.0 outputs using `sc.read_visium`. Although the issue is resolved. I am wondering if these functions are not maintained anymore. I am not familiar with Squidpy. But it seems to use these functions in its package. I would very much appreciate any clarification here.

**Comment by giovp** [comment]
hi @linhuawang ,

yes I'd suggest you to use squidpy for plotting, unfortunately the spaceranger 2.0 reading is not in main yet (will be by end of the week).
