### ISSUE TITLE
Request: Ability to subsample `AnnData` in backed mode

### ISSUE THREAD

**Issue by nleroy917** [scverse/scanpy#2495]
## Feature type

- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

## Request

The `scanpy.pp.subsample` function has been really useful for iteration, experimentation, and tutorials. However, I've found that sometimes I don't want to (or simply can't) read the entire `AnnData` object into memory before subsampling. As such, it would be nice to instantiate an `AnnData` object in backed mode, then subsample that directly.

### Current behavior:

```python
import scanpy as sc

adata = sc.read_h5ad("matrix/scatlas.h5ad", backed="r")
adata_sample = sc.pp.subsample(adata, fraction=0.01, copy=True)
```
yields:
```
ValueError: To copy an AnnData object in backed mode, pass a filename: `.copy(filename='myfilename.h5ad')`. To load the object into memory, use `.to_memory()`.
```
### Workaround:
A workaround I've found is by creating a boolean array and using boolean indexing to grab a random subset of rows from the `AnnData` object:

```python
import numpy as np

FRACTION = 0.01

np.random.seed(0)
random_bool = np.random.choice(
    [True, False], size=adata.shape[0], p=[FRACTION, 1 - FRACTION]
)

adata_sample = adata[random_bool, :]
adata_sample_mem = adata_sample.to_memory()
```

It's easy enough but would be nice to have within `scanpy` itself!

**Comment by eroell** [comment]
Hi,

thanks for the input and the nice description.

Agree that this would be nice to have within scanpy itself.

And agree, as you’ve shown in your example, that this should be the case when setting `copy=True`.

I have set up a draft PR for the moment, with a suggestion where the error message especially persists when `copy=False`; I’d suggest to keep it this way:

- Overwriting the backed file seems not to be the expected behaviour to me
- Writing a new file for backing would occur in a rather hidden manner, confusing the user or even unexpectedly further fill the disk at worst over time

**Comment by eroell** [comment]
With the merged PR which addresses the issue raised, this probably could be closed?
@ivirshup

**Comment by eroell** [comment]
We will close the issue for now, as based on the provided information and the discussion so far, it seems that the question has been addressed and hopefully resolved :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)

**Comment by nleroy917** [comment]
Thanks for this!
