### ISSUE TITLE
Define an extension mechanism

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#271]
We should have a discussion about this separate from #265.

There’s three options how to implement them

1. Python has a built-in way of registering “entry points” which might be suitable. [A tutorial](https://amir.rachum.com/blog/2017/07/28/python-entry-points/).

    ```py
    setup(
        # ...
        entry_points={
            'scanpy.extensions': ['myextension = my.extension.module'],
        },
    )
    ```

2. Some projects have a module like `scanpy.ext`. An extension is a module installed into there (which is possible in python):

    ```py
    setup(
        name='scanpy-ext-myextension',
        # ...
        packages=['scanpy.ext.myextension'],
    )
    ```

3. Some projects provide a config value like `scanpy.settings.extensions` to which module names can be `append`ed. Unlike the first two, this means the user has to enable them explicitly.

Pytest uses [both 1 and 3](https://docs.pytest.org/en/latest/writing_plugins.html) for its plugins.

Sphinx uses [both 1 and 3](http://www.sphinx-doc.org/en/master/extdev/index.html) for different things:  they want their “builders” to be automatically discovered and the other extensions to be explicitly enabled.

---

Another option for 2. is to use [flask’s approach](http://flask.pocoo.org/docs/1.0/extensiondev/) of just naming modules `scanpy_*` which is too cute and magic to me. Veto.

**Comment by fidelram** [comment]
This page summarizes the approaches mentioned by @flying-sheep together with examples to implement them: https://packaging.python.org/guides/creating-and-discovering-plugins/

My opinion is to implement the option that is easier for the plugin developer to facilitate adoption.

**Comment by flying-sheep** [comment]
Thank you! It talks about option 2 there: [#using-namespace-packages](https://packaging.python.org/guides/creating-and-discovering-plugins/#using-namespace-packages) and Option 1 here: [#using-package-metadata](https://packaging.python.org/guides/creating-and-discovering-plugins/#using-package-metadata)

The amount of work for plugin devs is completely covered in the first comment: one line added to `setup.py` each.

**Comment by falexwolf** [comment]
I think the current approach - a very simple interface as in `scanpy/tools/phate.py` and a bunch of others  is the easiest way to go for the developer.

So, I'd say we make a submodule `.ext` with the `.tools`, `.plotting`, `.preprocessing` substructure in it. We move things like `phate.py` into `scanpy/ext/tools`. We maintain backwards compat by still reexporting it in `scanpy.api`. The canonical way of calling these extension will be by importing `import scanpy.ext as sce` and people can use that extension namespace and call everything in the same way that they are used to. Users can look up extension tools on docs site like [this](https://scanpy.readthedocs.io/en/latest/api/index.html). It will also be clear to users that these extensions will require installing additional packages, which don't come with the default scanpy.

Of course, all of this needs none of the "extension mechanisms" mentioned above. But people really don't want to write actual "scanpy extensions"; they want to write their own packages and have them interface with scanpy so that convenient calls are enabled without the need to adapt to new conventions. For the scanpy users, the cool things is that a large number of tools can be quickly tested out.

If you don't mind, @fidelram and @flying-sheep, @Koncopd would go along and make this modest change.

**Comment by flying-sheep** [comment]
sounds good!

but of course, having a way to find packages that extend scanpy would be cool.

if we could search PyPI for a specific entry point type, and there was a scanpy entry point, that would make finding them a breeze.

or we do a `awesome-scanpy` repo that collects tutorials, extensions, and so on!

**Comment by flying-sheep** [comment]
We’re currently including many things into `scanpy.external`, which is probably enough …
