### ISSUE TITLE
The function of "sc.pp.filter" report an error "index out of range", why?

### ISSUE THREAD

**Issue by Silencewu1** [scverse/scanpy#2759]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

I just copied the code of official example, and changed the path to my own documents. But it seems that it doesn't work.  One folder of the total containing "barcodes", "features" and "matrix" has been attached below and the entire raw data comes from here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE139324

### Minimal code sample

```python
import scanpy as sc

path = r'RAW'
adata = sc.read_10x_mtx('RAW/HD PBMC_1/',var_names='gene_symbols', cache=True) 
adata.var_names_make_unique()
sc.pp.filter_cells(adata, min_genes=200)   
sc.pp.filter_genes(adata, min_cells=3)
```

### Error output

```pytb
IndexError: index (2444) out of range
```

### Versions

<details>

```

```

</details>

[HD PBMC_1.zip](https://github.com/scverse/scanpy/files/13404294/HD.PBMC_1.zip)
![2](https://github.com/scverse/scanpy/assets/147734739/0db8909d-84e4-41c5-8beb-09480d7adc3a)

**Comment by flying-sheep** [comment]
I can’t reproduce this with scanpy 1.9.6.

I’m going to close the issue and assume that you were using an old version since you didn’t fill out the versions box in the issue. If this happened using scanpy 1.9.6, please tell us and we’ll take another look.

![grafik](https://github.com/scverse/scanpy/assets/291575/97c20dc1-eaf6-4a65-80f8-6dff3455033d)
