### ISSUE TITLE
groups and reference in sc.tl.rank_genes_groups

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#278]
I'm afraid, I do not fully understand the documentation of `sc.tl.rank_genes_groups` when using the `groups` and `reference` arguments. Suppose that I have the categories `'1'`, `'2'`, `'3'` in my observation grouping `louvain`. Now, I run 
```python
sc.tl.rank_genes_groups(adata, 'louvain', groups=['1', '2'], reference='rest')
```
Would the reference now include cells from category `'3'`?

**Comment by falexwolf** [comment]
No, each of '1' and '2' is tested against the "rest" of the data, that is the union of '2' & '3' in the first, and the union of '1' and '3' in the second case. `groups` merely subsets which groups to look at, the default is to look at all, where 'all' will be equivalent to `['1', '2', '3']`.

**Comment by falexwolf** [comment]
It be cool if you made a PR to improve the documentation!

**Comment by fbnrst** [comment]
What worries me is that the behaviour you describe might not so for `method='logreg'`. Let's have a look at the following example:

```python
import scanpy.api as sc
adata = sc.datasets.blobs()
sc.pp.scale(adata)

sc.pp.neighbors(adata)
sc.tl.louvain(adata)

for method in ['t-test', 'logreg']:
    # first call, without groups
    sc.tl.rank_genes_groups(adata, 'louvain', method=method)
    sc.pl.rank_genes_groups_matrixplot(adata, n_genes=1)

    # first call, with groups    
    sc.tl.rank_genes_groups(adata, 'louvain', method=method, groups=['0', '1', '2'])
    sc.pl.rank_genes_groups_matrixplot(adata, n_genes=1)
```
As setting `groups` to `['0', '1', '2']` should not change the reference dataset, exactly the same marker genes should be detected for the first and the second call of `sc.tl.rank_genes_groups`. This is indeed true if I set the method to `t-test`. However, when setting method to `logreg`, I get other marker genes. Visually it appears to me that only the groups `['0', '1', '2']` are used a the reference set when using the method `logreg`.

**Comment by falexwolf** [comment]
Yes, right, for `logreg` you always regress on data that includes the respective group as this is not a differential test, but a regression. It's a shame that this is not evident from the documentation. It's sort of a recent alternative way of approaching the definition of marker genes and we should give it a bit more of a thought.

Regarding the behavior that is inconsistent up there, there is the following in the code by the person who extended this not long ago:
```
        # if reference is not set, then the groups listed will be compared to the rest
        # if reference is set, then the groups listed will be compared only to the other groups listed
        from sklearn.linear_model import LogisticRegression
        if len(groups) == 1:
            raise Exception('Cannot perform logistic regression on a single cluster.')
        adata_copy = adata[adata.obs[groupby].isin(groups_order)]        
        adata_comp = adata_copy
        if adata.raw is not None and use_raw:
            adata_comp = adata_copy.raw
        X = adata_comp.X

        clf = LogisticRegression(**kwds)
        clf.fit(X, adata_copy.obs[groupby].cat.codes)
```

You're right that logreg only includes the passed groups, if groups are passed. This should not be the case. I wonder why it's a problem in your specific case as I'd expect that 0, 1, 2 make up the whole data; but maybe the resolution in Louvain is somewhat set to a high value.

In any case, I'll change the implementation so that irrespective of whether `groups` is passed or not, one gets the same result.

**Comment by fbnrst** [comment]
Hi @falexwolf, thanks a lot for the clarifications. This helps me a lot. In the example I provided yesterday, `louvain` found 5 clusters, so 0, 1, 2 made up only part of the data. I should have provided the output as well to make this clear right away.

Concerning a PR for the documentation, I think I would wait until you will update the behaviour of `logreg`.
