### ISSUE TITLE
`FutureWarning` for the 1.11 to begin the process of switching leiden backend

### ISSUE THREAD

**Issue by ilan-gold** [scverse/scanpy#2935]
See: https://github.com/scverse/scanpy/issues/2865

**Comment by ivirshup** [comment]
I think we sorta already did this:

```python
sc.tl.leiden(adata)
/mnt/workspace/repos/scanpy/scanpy/tools/_leiden.py:144: FutureWarning: Use of leidenalg is discouraged and will be deprecated in the future.  Please use `flavor="igraph"` `n_iterations=2` to achieve similar results.  `directed` must also be `False` to work with `igraph`'s implementation.
  warnings.warn(msg, FutureWarning)
```

However, I do think the warning could be reworked

- [ ] Stack level should be set so the right line is shown
- [ ] Message should be more like:

> FutureWarning: In the future, the default backend for `leiden` will be `igraph` instead of `leidenalg`. To achieve the future defaults please pass: `flavor="igraph"` and `n_iterations=2`.  `directed` must also be `False` to work with `igraph`'s implementation.
>
> Note that results will be slightly different with the changed backend.

- [ ] We should only warn once, instead of every time leiden is called. Here's a util we defined in anndata for this (I think stolen from pandas?)

```python
def warn_once(msg: str, category: type[Warning], stacklevel: int = 1):
    warnings.warn(msg, category, stacklevel=stacklevel)
    # Prevent from showing up every time an awkward array is used
    # You'd think `'once'` works, but it doesn't at the repl and in notebooks
    warnings.filterwarnings("ignore", category=category, message=re.escape(msg))
```
