### ISSUE TITLE
Improve sc.read efficiency

### ISSUE THREAD

**Issue by Koncopd** [scverse/scanpy#303]
Improve sc.read\write memory usage and runtime.

**Comment by Koncopd** [comment]
Seems like the problem in the recursive calls of `_read_key_value_from_h5` in `_read_h5ad`

**Comment by falexwolf** [comment]
OK, very interesting! Can we have a video call on this? I'd be very interested in seeing a few benchmarks. 

At first sight, I'd say it shouldn't be that as the problem also appears when there are no "deep" recursions. I'd have thought that it could be this line that brings considerable performance gain (I sent you the reference in an email some time ago):

https://github.com/cmap/cmapPy/blob/7a2e18030f713865e8038bc7351e5ca44d061205/cmapPy/pandasGEXpress/parse_gctx.py#L332-L333

To get away from the recursions and to use `read_direct`, one needs to start exploiting the naming conventions in the `.h5ad` files. As these has have converged since about a year ago, it's save to do it, along with a table that explains the file format and provides an official reference. Right now, the only reference on the file format is [this](https://github.com/theislab/scanpy_usage/blob/master/170505_seurat/info_h5ad.md), which is ridiculous.

What do you think?

**Comment by Koncopd** [comment]
I haven't tried `read_direct ` yet but, in my opinion, it is not that helpful when we are reading the full array in memory without any type conversions. But i will check it of course.

Now it seems like the problem in the recursion as reading simple files with pre-specified paths is faster and takes less memory.
Also, it can be that the problem is somewhere in the step of transforming dictionary to AnnData, but i don't see where for now.

I'll check a few things, prepare readable benchmarks next week and we can have a call about it.

**Comment by falexwolf** [comment]
Awesome, thank you!

Making use of the file conventions, we can move completely away from the dict. The way this was done is a pain and is really only there for historical reasons (I started working with dicts and then @flying-sheep said I shouldn't do that but make a data container...).

So, I'm more than happy if the dict disappears completely and instead, one simply walks through the files and checks for the presence of certain predefined things. Of course, there will still be a lot of flexibility and a need to iterate through the `.uns` group, which can store dicts. But I hope that this won't be a performance bottleneck, as it's all small-scale.

**Comment by Koncopd** [comment]
Yeah, this was my plan also.

**Comment by Koncopd** [comment]
https://github.com/theislab/anndata/pull/85
https://github.com/Koncopd/anndata-scanpy-benchmarks/blob/master/memory_issue_huge.ipynb

I wasn't right about recursion, almost no effect. `read_direct` is efficient.

**Comment by falexwolf** [comment]
OK, this is absolutely great, thank you for actually doing the benchmarks! :smile:
