### ISSUE TITLE
error in dpt_scatter when 'groups' parameter set

### ISSUE THREAD

**Issue by snyquist2** [scverse/scanpy#32]
Hello,
When I call 'dpt_scatter' with the groups parameter I get the following error:
NameError: name 'names' is not defined

It looks like this is from line 230 in scanpy/plotting/ann_data.py and the 'names' variable just doesn't exist.
I'm assuming it should just be 'groups'?

Thanks,
Sarah

**Comment by falexwolf** [comment]
Hi Sarah,
thanks for the note and sorry about that; would you install a stable release from PyPi in the meanwhile `pip install scanpy`? I'm currently rewriting quite substantial parts and yes, this is clearly a bug I caused on the weekend; testing will also be more extensive in the future so that this stuff does happen anymore. This kind of stuff will also not happen on master branch in the future; but this rewriting goes along with building some [documentation](https://scanpy.readthedocs.io) and this builds from master... 
Cheers,
  Alex

**Comment by falexwolf** [comment]
Could you pull the current version (0.2.7) from github or install it via pip? Everything should be back to normal now.
