### ISSUE TITLE
scATACseq

### ISSUE THREAD

**Issue by manarai** [scverse/scanpy#447]
Hi,

Thanks for this amazing package.

I have been playing with scanpy on scATACSeq data generated from 10x. And in comparison to the cellranger analysis, I think analysis scanpy does pretty descent job and adds more possibilities. I would like to displays some peaks that are highly present if some clusters using the genome browser which scanpy seem to be able to do "I think" ( as shown below). Is it possible to the same thing but with the peak averaged/concatinated for all cells within the same cluster?

import matplotlib.pyplot as plt
genes =['chr15:101708546_101718131','chr11:117961932_117970696',
       'chr19:5821847_5852441','chr15:101422873_101429606',
       'chr17:39842811_39849028','chr13:6108971_6109684']
sc.pl.tracksplot(adata,genes,groupby='louvain', figsize=[40,50])

![atacseq](https://user-images.githubusercontent.com/39877296/51778958-d7e4c700-2147-11e9-88cd-78f3e100c75f.png)

**Comment by fidelram** [comment]
I don't think that what you want is possible.

sc.pl.tracksplot plots data in a way that resemble a genome browser track
but ist not because it does not understand coordinates. It simple groups
the cells by the given groupby condition and then plots the value of each
gene in a separate track. The y value is the gene expression (or in your
case the ATAC-seq value). The x coordinate, simple puts all cells one after
the other without any ordering.

**Comment by manarai** [comment]
Hum, I see. Thanks for the clarification!
