### ISSUE TITLE
sc.pp.normalize_per_cell

### ISSUE THREAD

**Issue by parashardhapola** [scverse/scanpy#47]
Hi,

May be I do not understand this clearly, but does the function `sc.pp.normalize_per_cell` not supposed normalize the counts? However when I run this function, I see that the values do not change at all. Am I doing something wrong here?

    raw_data.X.toarray().sum(axis=1)
   
    Out[18]:  array([ 23037.,  18883.,  20755., ...,  14785.,  20996.,   7604.], dtype=float32)

    normed_data = sc.pp.normalize_per_cell(raw_data, copy=True)
    normed_data.X.toarray().sum(axis=1)

    Out[19]: array([ 23037.,  18883.,  20755., ...,  14785.,  20996.,   7604.], dtype=float32)

Thanks

**Comment by falexwolf** [comment]
Sorry about that bug and thanks for reporting it. It only occurred with the `copy` parameter set, which is why no one noticed it till now.

The bug is fixed: https://github.com/theislab/scanpy/commit/f6a41f140a646c350ab12d8bd6aeff7499df069e

The docs are updated, there's now an example: http://scanpy.readthedocs.io/en/latest/api/scanpy.api.pp.normalize_per_cell.html

I wrote a test that checks that this doesn't break again in the future: https://github.com/theislab/scanpy/blob/f6a41f140a646c350ab12d8bd6aeff7499df069e/scanpy/tests/preprocessing.py#L11-L31

There will be a new release 0.3 with many improvements tomorrow.

Cheers,
  Alex

**Comment by parashardhapola** [comment]
Hi Alex,

Thanks for fixing this promptly. I will eagerly wait for the update.
I have another query related to usage of this function but I'll create a new issue for that.

Parashar
