### ISSUE TITLE
sc.pp.filter don't filter the same number between sc.1.3.7 and sc.1.4

### ISSUE THREAD

**Issue by juje11** [scverse/scanpy#501]
Hi all,

I have updated my scanpy to version 1.4 (was working on 1.3.7 before) and did not get the same filtering output using sc.pp.filter_ working with the same input dataset (10X).

By running in sc1.3.7: sc.pp.filter_genes(adata, min_counts=2)
->  267 genes were filtered out and I was able to follow up on my analysis until the end.

However, after switching to the new version, I could not get any filtering anymore. By scaling up, the first filtering I got was with a min of counts of 4 (sc.pp.filter_genes(adata, min_counts=4))
"filtered out 655 genes that are detected in less than 4 counts"

Not sure what is going on there and which setting I should use then.

Any feedback will be more than appreciated.

Thank you

**Comment by ivirshup** [comment]
@juje11, sorry about the late response. When I try `sc.pp.filter_genes` on `v1.3.7` and `v1.4.0` I get similar results. Here's what I've run:

```python
import scanpy.api as sc  # For v1.3.7
import scanpy as sc  # For v1.4+
adata = sc.datasets.pbmc3k()
sc.pp.filter_genes(adata, min_counts=2, copy=True)
```

In both v1.3.7 and v1.4 I get an AnnData object with 14745 genes.

If this issue is still occurring, could you please make a [minimal example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) of it?

**Comment by juje11** [comment]
Hey,

I had to fully switch to the new version to pursue my analysis. I have not tried since. The thing is the minimum count of genes to have the function running was not the same between the 2 versions.
For v1.3.7 I could do min_counts=2
For v1.4.0, I had to go for min_counts=4 otherwise the function was not running.

I have fully switch to the version 4 now, but this seems weird to me.

Thank you very much

Best regards

Julie

**Comment by LuckyMD** [comment]
Hi Julie,

Could it be that you saved your dataset after running `min_counts=2` so that when you reloaded it there were no more genes with `min_counts<2` in the dataset to filter out? 

Regarding the minimal example.. it would be good to show the different behaviour in a reproducible way (for example using a dataset from `sc.datasets`). We do not have the same error you do when running the function between scanpy 1.3.7 and 1.4.0.

**Comment by eroell** [comment]
Just came across this - as we haven't heard back after the followup, and its been quite a while, we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

Thanks for being a part of our community! :)
