### ISSUE TITLE
Getting rid of legacy umap code

### ISSUE THREAD

**Issue by falexwolf** [scverse/scanpy#522]
Now that UMAP is mature, we can get rid of the temporary frozen umap copy, I introduced a year ago for various reasons (see below).

Meanwhile, the following two functions can maybe direcly imported from UMAP, if not, we could make a PR there or use pynndescent?
https://github.com/theislab/scanpy/blob/07606455c524b38c4efec475a0d7ba87251754bb/scanpy/neighbors/__init__.py#L105
https://github.com/theislab/scanpy/blob/07606455c524b38c4efec475a0d7ba87251754bb/scanpy/neighbors/__init__.py#L258

There is a chance that this can also be solved with an import from UMAP.
https://github.com/theislab/scanpy/blob/07606455c524b38c4efec475a0d7ba87251754bb/scanpy/tools/_umap.py#L107

As just discussed, @Koncopd, can you look into this and make a PR that gets rid of the umap legacy code?

Thank you so much!
  Alex

PS: Just wrote an explanation for the reasons why I intorduced the duplicated code in the first place.
> The duplicated code in Scanpy came about as I wanted to very quickly move forward with a version 1.0 of Scanpy about a year ago. UMAP was just becoming available on GitHub and there wasn’t even a preprint, I think. It changed very quickly and there were dramatic bugs every now and then. Nonetheless it was clear that it’s a major improvement over existing solutions, both in terms of computational performance, quality of the result and ease of installation and use. I wanted to achieve two things: (i) I had to rewrite some parts of UMAP so that I could decompose it a neighbors computing and a dedicated embedding step; you know that in Scanpy, the neighborhood graph is used for many other things other than for the embedding (clustering and trajectory inference). I also added the Gaussian kernel solution that I had before switching to a “UMAP backend” for `pp.neighbors`; which was needed so that results for DPT could be reproduced. All of this would have been quite a discussion with Leland. Until we would have had settled on the “Scanpy needs” that certainly weren’t aligned with the development of an independent young package, PRs would have been integrated to much time would have been lost. Finally, I wanted absolute reproducibility for Scanpy users, which could only be achieved by “freezing the code”.  So, I asked Leland whether he is OK if I add a frozen version of umap as an intermediate solution.

**Comment by falexwolf** [comment]
@tomwhite: This is the project I was mentioning before. We've discussed for months already, but we didn't really kick it off. Now there is bandwidth and it's the top priority.

**Comment by gokceneraslan** [comment]
There might be couple of things that's available in umap but not in pynndescent such as sparse matrix support https://github.com/lmcinnes/pynndescent/issues/6 Since we typically use PCs, it's mostly fine. But in cases where users do sc.pp.neighbors(., use_rep="X") with a sparse adata.X this can be a problem. My 2 cents 😊

**Comment by falexwolf** [comment]
Thanks, @gokceneraslan!

**Comment by tomwhite** [comment]
Thanks for tackling this one @falexwolf.

I didn't realise until recently that umap has a copy of pynndescent too. However, I think it would be possible for scanpy to depend on both umap and pynndescent packages, and use the latter for generating the knn graph directly. This would mean new features in pynndescent (like the threading support) could be used from scanpy.

**Comment by falexwolf** [comment]
@Koncopd, could we have a meeting or VC on the progress here? Let's discuss via email. 🙂 

@tomwhite, any updates from @lmcinnes regarding integrating the distributed version of `pynndescent` into UMAP itself? I'm not 100% convinced to mingle with private functions within UMAP that might eventually break (another reason for why I copied over code from UMAP back in January/February 2018). It would be nice to have Leland's OK for adding distributed aspects to the package. Scanpy would then just make use of them...

@tomwhite, by this, also many other single-cell packages (many of them use UMAP these days) would profit from the new distributed computing capabilities.

**Comment by Koncopd** [comment]
@falexwolf 
Hi, Alex. What i figured out for now.

https://github.com/theislab/scanpy/blob/07606455c524b38c4efec475a0d7ba87251754bb/scanpy/neighbors/__init__.py#L105
This can be replaced by importing this
https://github.com/lmcinnes/umap/blob/a858c6322a3e682d8daf9c17e13ac023f3e18cfa/umap/umap_.py#L148

https://github.com/theislab/scanpy/blob/07606455c524b38c4efec475a0d7ba87251754bb/scanpy/neighbors/__init__.py#L258
This is basicly this
https://github.com/lmcinnes/umap/blob/a858c6322a3e682d8daf9c17e13ac023f3e18cfa/umap/umap_.py#L329
But this `fuzzy_simplicial_set` doesn't calculate `distances`, only `connectivities`. What is the right approach to solve this? Writing PR to umap that adds `distances` as a return value for `fuzzy_simplicial_set`?

https://github.com/theislab/scanpy/blob/07606455c524b38c4efec475a0d7ba87251754bb/scanpy/tools/_umap.py#L107
This line can be directly imported from umap of course, but now their `simplicial_set_embedding` requres also `adata.X` as an input, because the case with the number of connected components > 1 is treated differently. It should not be a problem as we have this in adata. I comment it just because this changes the logic a bit.

**Comment by tomwhite** [comment]
@Koncopd this looks correct to me.

For `compute_connectivities_umap`, it could be left in `scanpy/scanpy/neighbors/__init__.py` until UMAP's `fuzzy_simplicial_set` returns distances too. (In other words, the change to `fuzzy_simplicial_set` doesn't have to block depending on UMAP.)

**Comment by falexwolf** [comment]
Cool, @Koncopd! Looks good! @tomwhite, thank you for your comments!

@lmcinnes: are the functions like `nearest_neighbors` and `fuzzy_simplicial_set` stable enough to be used externally? They are not re-exported to the user API; a year ago, I was afraid that code that depended on them might break if changes were made, even if it's just renaming parameters etc. Do you announce chances that might break backwards compat for these functions?

@Koncopd 
> But this fuzzy_simplicial_set doesn't calculate distances, only connectivities. What is the right approach to solve this? Writing PR to umap that adds distances as a return value for fuzzy_simplicial_set?

I'd guess that @lmcinnes wouldn't want to blow this up with another return value. Why can't we just use the return value for `nearest_neighbors` and construct the distance graph as it's done right now in Scanpy? In any case, it doesn't block depending on UMAP...

**Comment by Koncopd** [comment]
@falexwolf 
Maybe just an additional optional argument which allows to return distances is fine?
But, yes, you are right, we can just repeat [this loop](https://github.com/theislab/scanpy/blob/07606455c524b38c4efec475a0d7ba87251754bb/scanpy/neighbors/__init__.py#L280) to get the distances matrix for the graph. So we have 2 loops (one in umap's  `fuzzy_simplicial_set` and one additional in our custom function) instead of one, but maybe it is better than cluttering basicly the internal function of umap.

**Comment by Koncopd** [comment]
https://github.com/theislab/scanpy/pull/576
