### ISSUE TITLE
Feature request - DPT predict

### ISSUE THREAD

**Issue by dflores2** [scverse/scanpy#53]
Thanks for you work!

There is a feature that I would be nice to have. Once the DPT has been calculated, it would be nice to be able to "predict" (like in the R package destiny) new data into  the calculate DifussionMap . It would be great to include a label that tells apart the new cells from the already existing ones.

Thanks

**Comment by falexwolf** [comment]
Oh, sorry about having completely forgot about this issue...

Instead of providing a "mapping into diffmap" method, we will provide generic methods for mapping new data into the fundamental single-cell graph, which is the basis for all embeddings. So, we do not plan to provide something for diffusion maps only.

While this generic "mapping new data into existing data" will take another while, you do the most consistent thing if you merge your dataset, recompute the graph and embed that merged graph.
