### ISSUE TITLE
Plotting the expressions of several markers on a single UMAP plot

### ISSUE THREAD

**Issue by ParisaMa** [scverse/scanpy#532]
Hi,

Would it be possible to plot several markers on a single UMAP plot instead of having a plot for each of them separately? The color parameter of the pl.umap function takes the markers as a list of strings and plots them individually.  

Thanks,
Parisa

**Comment by LuckyMD** [comment]
Hi @ParisaMa,

So you want a single umap visualization with the the sum of several marker genes (or some related score) plotted on top of this? I'm a bit sceptical regarding how that would be helpful (you may want to know which cells have 0 values for a particular marker), but there is a way to do this. 

You can use `sc.tl.score_genes(adata, gene_list, score_name='my_score')` to calculate a gene score for all the genes you wish to plot at the same time, and then visualize that score on a umap via: `sc.pl.umap(adata, color='my_score')`. That wouldn't give you the sum of the gene expression values, but the average expression minus an average expression of a random gene set.

If you just want to add the gene expression values, you can of course also create your own score via something like this:
`adata.obs['my_score'] = adata.X[:,my_genes].sum(1)` 
and plot that. You may have to check what format is expected for `my_genes` though.

**Comment by ParisaMa** [comment]
Hi @LuckyMD 

Thanks for your reply! I'm actually interested in the distribution of a bunch of markers instead of just looking at one. I have a set of markers for a specific population (extracted from a study) and would like to know how how their expressions look like on my clusters (to see if I actually have that population). However, because of the differences in the scales, it can be tricky and kind of different than just adding them up, what I want is more like scaling them altogether. Is this what that score_genes functions that you suggested does?

**Comment by LuckyMD** [comment]
Hi @ParisaMa,

I think then you'd be better off using `sc.pp.scale()` to create z-scores and then just using the second method I suggested, but using `.mean(1)` instead of the sum. That way you take the average z-scres of the marker gene expression values.

I think it would probably be better to look at this in a violin plot though, if you really want to see the marker gene expression distributions.

**Comment by myaqubi** [comment]
Hi Parisa and @LuckyMD

I hope you are doing well. 

I have the same question as Parisa. I am wondering if the code that you suggested should be implemented in Seurat or Python? If it's not from Seurat, does Seurat have a code for that?

Parisa, did you figure it out?

Thank you so much

**Comment by LuckyMD** [comment]
Hi,
We don't have a simple function for this atm. But you could check out the dotplot, maybe that already does what you'd like. I'm not sure about Seurat, as I predominantly use scanpy.

**Comment by myaqubi** [comment]
Thanks.

**Comment by chris-rands** [comment]
For anyone coming here, i think there was a typo in the 2nd suggestion:
```
adata.obs['my_score'] = adata[:,my_genes].X.sum(1)
```

**Comment by LuckyMD** [comment]
yes, thanks :).

**Comment by sfortma2** [comment]
Just to follow-up because I also had a similar question to the OP. Here's one way to plot several marker genes in different colors on the same UMAP plot. The trick is to make different colormaps that have an alpha gradient so that cells with NA expression appear transparent. Then just use matplot axes to merge the images. The only issue is that Scanpy doesn't yet allow you to remove colorbars for continuous variables, so the multiple colorbars can throw off the scaling, which you can work around by changing the figure parameters.

```
#make red colormap
colors2 = plt.cm.Reds(np.linspace(0, 1, 128))
colorsComb = np.vstack([colors2])
mymap = colors.LinearSegmentedColormap.from_list('my_colormap', colorsComb)
my_cmap = mymap(np.arange(mymap.N))
my_cmap[:,-1] = np.linspace(0, 1, mymap.N)
my_cmap = colors.ListedColormap(my_cmap)

sc.pl.umap(adata, color=['AIF1'], use_raw=True, color_map=my_cmap, show=False, frameon=False)
```
![image](https://user-images.githubusercontent.com/56206488/126086651-df0d46c9-5f1d-4b64-8109-f82cd1feb9cb.png)

```
#make blue colormap
colors2 = plt.cm.Blues(np.linspace(0, 1, 128))
colorsComb = np.vstack([colors2])
mymap = colors.LinearSegmentedColormap.from_list('my_colormap', colorsComb)
my_cmap2 = mymap(np.arange(mymap.N))
my_cmap2[:,-1] = np.linspace(0, 1, mymap.N)
my_cmap2 = colors.ListedColormap(my_cmap2)

sc.pl.umap(adata, color=['CD3E'], use_raw=True, color_map=my_cmap2, show=False, frameon=False, vmax=3)
```
![image](https://user-images.githubusercontent.com/56206488/126086666-a0828d86-d943-47b8-8207-eb42aeb32e4b.png)

```
#make green colormap
colors2 = plt.cm.Greens(np.linspace(0, 1, 128))
colorsComb = np.vstack([colors2])
mymap = colors.LinearSegmentedColormap.from_list('my_colormap', colorsComb)
my_cmap3 = mymap(np.arange(mymap.N))
my_cmap3[:,-1] = np.linspace(0, 1, mymap.N)
my_cmap3 = colors.ListedColormap(my_cmap3)

sc.pl.umap(adata, color=['CD79A'], use_raw=True, color_map=my_cmap3, show=False, frameon=False)
```
![image](https://user-images.githubusercontent.com/56206488/126086688-66a3af40-ecc1-4b2e-a3e4-8038f7f207b0.png)

```
#make purple colormap
colors2 = plt.cm.Purples(np.linspace(0, 1, 128))
colorsComb = np.vstack([colors2])
mymap = colors.LinearSegmentedColormap.from_list('my_colormap', colorsComb)
my_cmap4 = mymap(np.arange(mymap.N))
my_cmap4[:,-1] = np.linspace(0, 1, mymap.N)
my_cmap4 = colors.ListedColormap(my_cmap4)

sc.pl.umap(adata, color=['VWF'], use_raw=True, color_map=my_cmap4, show=False, frameon=False, vmax=5)
```
![image](https://user-images.githubusercontent.com/56206488/126086713-d8b24873-f3ea-4067-8573-99241db1c9b2.png)

```
#combine images to one UMAP
plt.rcParams['figure.figsize']=(6,4)
ax = sc.pl.umap(adata, color=['AIF1'], use_raw=True, color_map=my_cmap, show=False, vmax=5, frameon=False)
ax = sc.pl.umap(adata, color=['CD3E'], use_raw=True, color_map=my_cmap2, show=False, vmax=3, frameon=False, ax=ax)
ax = sc.pl.umap(adata, color=['CD79A'], use_raw=True, color_map=my_cmap3, show=False, frameon=False, ax=ax)
ax = sc.pl.umap(adata, color=['VWF'], use_raw=True, color_map=my_cmap4, show=True, frameon=False, ax=ax, vmax=5)
```
![image](https://user-images.githubusercontent.com/56206488/126086774-4c92352c-83b2-4c58-9874-6ff61660e22d.png)

Hope this helps someone!
