### ISSUE TITLE
feature request - `restrict_to` option for leiden clustering

### ISSUE THREAD

**Issue by mbuttner** [scverse/scanpy#582]
Hi, 
I was wondering, if you can synchronize the functionality of the louvain and leiden clustering algorithm implementations. 
`sc.tl.louvain` has the `restrict_to` parameter, which allows subclustering of a specific cluster (set), while `sc.tl.leiden` does not (Note: I have `scanpy==1.4+18.gaabe446`). 
I'd be happy to have that. 

Best,
M

**Comment by flying-sheep** [comment]
sure, sounds sensible! related issue: #570

**Comment by fbrundu** [comment]
Hi! I just wrote a quick solution in https://github.com/theislab/scanpy/pull/586
I tested it manually and it seems to work (I used louvain code as template).
I assumed it could be interesting to work on a separate leiden function, due to possible argument clashes with louvain, instead of merging the two functions together.

**Comment by fbrundu** [comment]
It should be fixed on master by https://github.com/theislab/scanpy/pull/586

**Comment by flying-sheep** [comment]
Great, thank you again!
