### ISSUE TITLE
Can't find mito_genes

### ISSUE THREAD

**Issue by ikohideonbush** [scverse/scanpy#639]
I am trying to follow this tutorial 
https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html,
but some error just happened in the initial  QC stage.
After running:
mito_genes = adata.var_names.str.startswith('MT-')
adata.obs['percent_mito'] = np.sum(
    adata[:, mito_genes].X, axis=1).A1 / np.sum(adata.X, axis=1).A1
and plot the violinplot,
I just get this graph
![percent_mito](https://user-images.githubusercontent.com/41959955/57546005-6ba47100-738e-11e9-8cb6-c6a18b89f8dd.png)

I felt somthing wrong and checked this:
__________________________________________________________________________________________________
[In]    np.sum(adata.obs)
[Out]    n_genes         14918559.0
**percent_mito           0.0**
dtype: float64

__________________________________________________________________________________________________
It seems that scanpy just didn't recognized the mitogene or removed it, but there's nothing wrong when I used Seurat.

I have no idea where the error is located and need your help. Thanks in advance.

**Comment by LuckyMD** [comment]
Hi,

Can I ask if you are using the data from the tutorial? If not, then there are a a few potential sources of error here:
1. You may have not aligned against the mitochondrial genome (Cell Ranger versions < 2.0 don't do this)
2. You may have mouse data, in which case it should be lower case `mt-` instead of `MT-`.
3. Your data may have been pre-processed to take out mitochondrial genes.

I recall looking through quite a few datasets where there were really no mitochondrial genes. Scanpy doesn't automatically filter out mitochondrial genes. You could also check if you have any mitochondrial genes by just outputting this line: `adata.var_names.str.startswith('MT-')`.

**Comment by ikohideonbush** [comment]
> Hi,
> 
> Can I ask if you are using the data from the tutorial? If not, then there are a a few potential sources of error here:
> 
> 1. You may have not aligned against the mitochondrial genome (Cell Ranger versions < 2.0 don't do this)
> 2. You may have mouse data, in which case it should be lower case `mt-` instead of `MT-`.
> 3. Your data may have been pre-processed to take out mitochondrial genes.
> 
> I recall looking through quite a few datasets where there were really no mitochondrial genes. Scanpy doesn't automatically filter out mitochondrial genes. You could also check if you have any mitochondrial genes by just outputting this line: `adata.var_names.str.startswith('MT-')`.

It really helps! Thanks very much!(by the way I am using zebrafish data and it still should be lower case, but I was just not aware of this)
