### ISSUE TITLE
Rank_genes_groups p-values of 1?

### ISSUE THREAD

**Issue by outlace** [scverse/scanpy#701]
After running `rank_genes_groups` with 100 genes and 30 clusters, the `adata.uns['rank_genes_groups']['pvals_adj']` results in a `100x30` array of p-values. Each column is a cluster, so the first row has the top-scoring genes for each cluster. But if you look at the p-values, some of them are 1. And the p-values do not seem to increase as you go down the rows, but the scores do decrease as you go down the rows. 

So if we want to just isolate marker genes that are statistically significant at some threshold, how do we do that?

**Comment by outlace** [comment]
Ideally I could get something like a `Number of clusters x Number of Genes` array of p-values that shows the p-value of fold change for each gene for gene cluster so I can pick out the statistically significant genes for each cluster

**Comment by ivirshup** [comment]
I believe the array you're getting should be the `cluster x genes` array you're looking for. And the p-values should be increasing as the list descends (with a max of 1). Could you give an example of what your results looks like, in particular, showing how they differ from what you expect?

Admittedly, the differential expression data structure is kinda hard to work with at the moment. If you're on the master branch of `scanpy` you should be able to use `sc.get.rank_genes_groups_df(adata, group_key)` for an easier to use structure. This also has key-word arguments for setting a p-value cutoff.

**Comment by LuckyMD** [comment]
Looking forward to playing with the `sc.get` stuff :). key-word arguments sound great!

**Comment by suryadipto** [comment]
When I run sc.rank_genes_groups() on my gene expression data, I do get separate matrices for names, scores, pvals, and pvals_adj. However, the scores don't match the pvals. In other words, with decreasing pvals, we don't always have increasing score. I did check out the description on the main documentations page, and they say they're calculating the zscores underlying the distribution, however if that's the case shouldn't it always be higher with decreasing pval? Also, I went through the code: it looks like they're calculating the scores on the absolute values instead of the real values--why is this? Are the scores basically U1 values corresponding to the pvalues, in whcih case once again lower pvalues should always have higher scores right?
ares calculated from the p-values? What'e the relation between the two.

I have ran sc.rank_genes_groups() on my gene expression data, and I have generated the matrix for cluster-1 versus the rest, for reference. You can see that one, the pavlues don't increase as we go down the rows; and two, the scores seem kinda arbitrary to the p-values. What am I missing here? Thanks a lot, and sorry for the wordy question.

[ClusterOneVsRest.csv](https://github.com/scverse/scanpy/files/12242378/ClusterOneVsRest.csv)

**Comment by eroell** [comment]
For future readers looking for a response to the last question, please hop to the response to issue #2586.

**Comment by eroell** [comment]
Based on the provided information and the discussion so far, it seems that the question has been addressed and resolved.

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
