### ISSUE TITLE
Embedding density limited to 10 groups?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#719]
@LuckyMD, why does `sc.tl.embedding_density` limit itself to running on labels with 10 or less categories?

**Comment by LuckyMD** [comment]
Just for reasons of practicality. I figured it would create a mess to visualize more than 10 plots with different groups. Also, you should have sufficient cells per group to make the kde calculation meaningful. That will depend on the number of cells as well though.

**Comment by ivirshup** [comment]
On the cells per group, is there some measure we could use to have a sense of whether the KDE is representative, potentially throwing a warning if it's below a threshold?

I came across this when I wanted to look at the densities of two clusters (out of a clustering solution with ~15) without changing the relative positions of those clusters in the embedding. If the computational expense of the KDE doesn't become prohibitive, I think it'd be reasonable to support this case. I also think we can trust the user to choose how many plots they want to generate.

**Comment by ivirshup** [comment]
@LuckyMD, just got reminded of this by a potential solution to the many groups issues. Topological KDE plots:

![image](https://user-images.githubusercontent.com/8238804/69897510-29319880-13a1-11ea-8086-ad5f4ca2d137.png)

Unfortunately, I'm not sure I trust how plotly is generating them, but they do look nice.

**Comment by LuckyMD** [comment]
This looks really cool. I don't see how this is a solution to the many groups issue though. Especially as you'd likely have the densities of many groups overlapping in the same area.

Otherwise, I don't really know of a heuristic to assess whether the kde is reliable. I am okay with removing the 10 groups threshold and just letting the user deal with the mess... but maybe that's not the kindest thing to do. This is essentially a discussion of flexibility vs ease-of-use. Might merit a more principled discussion.

**Comment by ivirshup** [comment]
I think it can help for when groups overlap. When two solid colors overlap, you lose visual information. Here you may be able to plot multiple groupings on the same plot, since there are no fills so it's more likely you can disambiguate the boundaries when overlaps occur.

**Comment by falexwolf** [comment]
Having run into the limitations of constraining to 10 categories for quite some time, and now seeing @sunnysun515 write a wrapper that brings the functionality and produces meaningful plots: I'd strongly advocate for letting the user decide!

To address concerns raised above, I added a warning to the docstring that enough cells per category are needed for a meaningful estimate: https://github.com/theislab/scanpy/pull/1936/commits/760a967b57b93b0da3296d98430509627f3a80d7

[Imagining a warning showing up whenever the function is called seems more disruptive.]

Otherwise, it'd be great if @LuckyMD and @sunnysun515 could take a look in addition to Isaac: https://github.com/theislab/scanpy/pull/1936
