### ISSUE TITLE
Concatenate files issue

### ISSUE THREAD

**Issue by ccruizm** [scverse/scanpy#751]
Good day!

I have been trying to run the single cell tutorial but have had some issues concatenating several datasets. I am able to read successfully the first data set. However, once I want to load the other datasets, there is a problem concatenating the files. 

<img width="749" alt="Screenshot 2019-07-27 at 12 49 49" src="https://user-images.githubusercontent.com/37718031/61993507-06971800-b06d-11e9-815e-acf667f818a5.png">
<img width="730" alt="Screenshot 2019-07-27 at 12 41 58" src="https://user-images.githubusercontent.com/37718031/61993416-edda3280-b06b-11e9-9a4f-7d4a1259cd47.png">

This happens in the first loop to load all the datasets. If I run only one dataset the same error `(unsupported operand type(s) for +: 'int' and 'str')` showed up when I plot some data quality summary plots:

For instance:
`p1 = sc.pl.scatter(adata, 'n_counts', 'n_genes', color='mt_frac') p2 = sc.pl.scatter(adata[adata.obs['n_counts']<10000], 'n_counts', 'n_genes', color='mt_frac')`
`adata = adata[adata.obs['mt_frac'] < 0.2]
print('Number of cells after MT filter: {:d}'.format(adata.n_obs))`
`sc.pp.filter_cells(adata, min_genes = 700)
print('Number of cells after gene filter: {:d}'.format(adata.n_obs))`

I am using data generated by 10x V3 and CellRanger v3.0.2. I really do not know where the problem is. 

I really appreciate any advice/help to solve this issue.

Thanks in advance

**Comment by stepbystep99** [comment]
sudo rm  /media/ubuntu/d0b69706-4d42-40a3-b531-382041477d35/home/cns/biosoft/cellranger/cellranger-3.0.2/deng2_count_myself -fr







At 2019-07-27 18:48:50, "Cristian" <notifications@github.com> wrote:


Good day!

I have been trying to run the single cell tutorial but have had some issues concatenating several datasets. I am able to read successfully the first data set. However, once I want to load the other datasets, there is a problem concatenating the files.

This happens in the first loop to load all the datasets. If I run only one dataset the same error (unsupported operand type(s) for +: 'int' and 'str') showed up when I plot some data quality summary plots:

For instance:
p1 = sc.pl.scatter(adata, 'n_counts', 'n_genes', color='mt_frac') p2 = sc.pl.scatter(adata[adata.obs['n_counts']<10000], 'n_counts', 'n_genes', color='mt_frac')
adata = adata[adata.obs['mt_frac'] < 0.2] print('Number of cells after MT filter: {:d}'.format(adata.n_obs))
sc.pp.filter_cells(adata, min_genes = 700) print('Number of cells after gene filter: {:d}'.format(adata.n_obs))

I am using data generated by 10x V3 and CellRanger v3.0.1. I really do not know where the problem is.

I really appreciate any advice/help to solve this issue.

Thanks in advance

**Comment by LuckyMD** [comment]
I see that you have a column in `adata.var` called '2'. Is that in each of your dataset files? You may need to rename that column to a non-integer name before concatenating.

An easier way of dealing with this might just be to use `sc.read_10x_mtx()` to read in the data.

**Comment by ccruizm** [comment]
Indeed, that was the issue! Thanks for your reply and suggestion.
