### ISSUE TITLE
Error filtering 'Boolean index not valid'

### ISSUE THREAD

**Issue by cartal** [scverse/scanpy#768]
Hi, 

I have been trying to apply filters to an object within `scanpy` and I got the following error (See attachment). 

Do you have an idea of what's going on? 

![image](https://user-images.githubusercontent.com/3297906/62468966-2aeea500-b78f-11e9-809f-ab0c0c22b0b7.png)

**Comment by LuckyMD** [comment]
This seems related to #728 . I think it's fixed on anndata master, but that also has some intentional breaking changes.

**Comment by flying-sheep** [comment]
Does it work with anndata master?

**Comment by eroell** [comment]
As we haven't heard back after the followup we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
