### ISSUE TITLE
Covariates in combat batch correction

### ISSUE THREAD

**Issue by SamueleSoraggi** [scverse/scanpy#780]
Hi,

I wonder how one should use the `covariates` argument of combat. I cannot find an example or more guidance about it.

Cheers,
Samuele

**Comment by gokceneraslan** [comment]
Hi Samuele,

`covariates` argument refers to the additional covariates (biological or technical) that are used in the model fit. It's the `mod` parameter in the R function combat (https://www.rdocumentation.org/packages/sva/versions/3.20.0/topics/ComBat) and `X` in equation 2.1 in Johnson et al. 2007, https://academic.oup.com/biostatistics/article/8/1/118/252073. Since only the batch variable is "regressed out" from the gene expression, adding extra covariates changes the way batch effect coefficient is estimated.

By the way, https://scanpy.discourse.group is a better place to ask questions and start such discussions :)

**Comment by gokceneraslan** [comment]
I extended the documentation a bit now, see https://github.com/theislab/scanpy/commit/c7e58e3a8e32b7f395e25267cd3cba684d6d40c4.
