### ISSUE TITLE
Fix and export or delete rna_velocity

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#792]
We have unused and untested RNA velocity code in #130.

Our plotting functions accept the `arrows` argument which expects a `Delta_` from velocyto.

I guess everything here is superseded by scvelo, so should we just get rid of the `rna_velocity` code and make `arrows` work with scvelo?

**Comment by ivirshup** [comment]
I think it would make sense to fully delegate this stuff to velocyto. Does the arrows argument currently work?

**Comment by gokceneraslan** [comment]
#694 is not the correct pr/issue I guess. Where did the RNA velocity code come from?

**Comment by fidelram** [comment]
maybe @VolkerBergen can comment on this. My opinion is that the `rna_velocity` code should be deleted, if I remember correctly is not even functional.

**Comment by VolkerBergen** [comment]
brief recap: https://github.com/theislab/scanpy/pull/130 was the initial work on integrating RNA velocity into scanpy, which was a slimmed version of velocyto; yet not working well due to its simplification and several missing required processing steps. Consequently, and with the additional objective of extending velocyto, we outsourced that to scvelo.

For directed paga this is already adjusted. I think we missed https://github.com/theislab/scanpy/blob/740c4a510ec598ab03ff3de1d9b1c091f0aac292/scanpy/plotting/_utils.py#L334; the convention became `'velocity_' + basis ` (instead of `'Delta_' + basis `). This is used only for scatter plots, if I get it correctly. The velocity plotting modules within scvelo have been extensively optimized, thus questionable whether still needed within scanpy. Anything else I am missing?

**Comment by flying-sheep** [comment]
@gokceneraslan Whoops, it’s #130, no idea why I linked the wrong one.

> if I remember correctly is not even functional.

@fidelram You do, the module containing the function doesn’t import things used in the function. So at least that’s broken, maybe more.

**Comment by LuckyMD** [comment]
@VolkerBergen Directed PAGA is already a thing? Is there an example script for this somewhere?

**Comment by VolkerBergen** [comment]
It's **a** thing, not yet **the** thing. For directed PAGA follow [this](https://github.com/theislab/paga/issues/11) while always double checking with your single cell velocities as it is not yet perfectly robust.
