### ISSUE TITLE
Unpin matplotlib version once possible

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#849]
As @fidelram said in https://github.com/theislab/scanpy/pull/661#issuecomment-496144015, we have to wait until matplotlib/matplotlib#14298 is fixed.

It seems to be in matplotlib’s 3.1.2 milestone, so maybe we can just set the dependency to “matplotlib == 3.0.0 or matplotlib >= 3.1.2”

This originally came up in #663, and then later in e.g. #787

**Comment by ivirshup** [comment]
This seems to be working now. Given that matplotlib updates are known to introduce bugs, I'm not sure we want to pin matplotlib to `3.3.3`. I'm concerned that's too strong of a restriction, since it's likely there's someone out there who needs to use an older version.

Right now this is causing CI to fail, since there's a canary test that fails when the function works 😆.
