### ISSUE TITLE
Unable to change vmax in scanpy.pl.scatter

### ISSUE THREAD

**Issue by alm8517** [scverse/scanpy#875]
Hi Scanpy team,

A potentially silly question. I'm having problems changing vmax in sc.pl.scatter.

I want to set 'dpt_pseudotime' vmax to 0.5, similar to how vmax and vmin can be changed, for example, in sc.pl.umap.

I tried the following:

with axes_style({'axes.grid': False}):
  sc.pl.scatter(adata_0_1, x='Vim', y='Lyz2', color='dpt_pseudotime', size=5, use_raw=False, 
  color_map='RdYlBu_r', vmax=0.5)

But get the following error:

![image](https://user-images.githubusercontent.com/49629901/66955933-64fee180-f031-11e9-90c2-0f12a392786b.png)

I read in the scanpy.pl.scatter documentation that kwargs can be used to set vmax. I tried this approach, but got the same result as above:

kwargs={'vmax':0.5}

with axes_style({'axes.grid': False}):
 sc.pl.scatter(adata_0_1, x='Vim', y='Lyz2', 
 color='dpt_pseudotime', size=5, use_raw=False, color_map='RdYlBu_r', **kwargs)

I tried to find a solution online with no success. Any help/suggestions will be appreciated

P.S: This is my first post and I'm a huge fan of your package. Keep up the great work!

**Comment by flying-sheep** [comment]
Hi! thank you for the praise! I’m afraid this is a documentation bug!

We had a bit of an issue with documented parameters not matching real ones. It’s fixed in the [latest docs](https://icb-scanpy.readthedocs-hosted.com/en/latest/api/scanpy.pl.scatter.html) where `scatter` doesn’t say it has a `kwargs` or `vmax` parameter.

We should simplify our plotting. @VolkerBergen has some nice plotting functions, but implemented them as part of scvelo, not scanpy as he should have :stuck_out_tongue_winking_eye:

**Comment by VolkerBergen** [comment]
Soonish! ;) For now, you can do that through scvelo (scvelo.org) in analogy to scanpy with
`scv.pl.scatter(adata, ..., vmax=.5)`. 

There's probably also a way to manually set `pl.clim()` or `ax.set_clim()` in scanpy..

**Comment by flying-sheep** [comment]
> Soonish!

awesome!

> There's probably also a way […]

Yeah, the function should return an `Axes` object (at least if `show=False`, but idk why it doesn’t just always returns that)
