### ISSUE TITLE
Wrong dependencies on bioconda for 1.4.4

### ISSUE THREAD

**Issue by LustigePerson** [scverse/scanpy#876]
I just noticed that matplotlib 3.1.1 is installed when using conda to install scanpy 1.4.4.
In your requirements you state that this breaks the scatter plot.
In the repodata from bioconda however it seems like there are very old dependencies that were not changed when new scanpy versions were included. So still the dependency there ist matplotlib>=2.2.

**Comment by flying-sheep** [comment]
Well, @biocondabot doesn’t know this. Please report in https://github.com/bioconda/bioconda-recipes/blob/master/recipes/scanpy/meta.yaml

PS: Since I know from which company you are, some free consulting :wink:: Installing conda inside of docker images wouldn’t be a pain I’d be willing to go through. Conda installs a whole parallel universe of native libraries and python installations. A container is much easier to debug and much lighter on the resources if you use a regular python installation and pip. I’d rather [host a small PyPI](https://packaging.python.org/guides/hosting-your-own-index/) to hold precompiled wheels of louvain-igraph and so on than use conda.

**Comment by LustigePerson** [comment]
Thanks for the tip @flying-sheep. ;) I will consider this. 
And regarding Bioconda, I was not aware how the package actually comes into bioconda. So the @BiocondaBot is not chekcing the requeiremts. Really strange.

**Comment by flying-sheep** [comment]
Yeah, someone creates a package and whenever a new release appears on PyPI, the bot makes a PR that increases the version number in the build recipe. A human then checks if everything works and merges. In this case that human didn’t check the dependencies changing (very understandable, it’s draining to search where they’re defined and compare manually multiple times per day)

You could simply do a quick PR that updates dependencies and build number and I’m sure they’ll quickly merge it.
