### ISSUE TITLE
plotting overlay of 2 genes on tsne

### ISSUE THREAD

**Issue by koalap-2018** [scverse/scanpy#912]
Hi guys,

I would like to use the sc.pl.tsne to color the TSNE with the expression of 2 genes but in the same plot... currently i ran sc.pl.tsne(adata, color=['geneA','geneB']). This gives 2 tsne's but i would like to visualize things in just one.

thanks!

**Comment by LuckyMD** [comment]
Hi,

You could just set an `adata.obs` field with the exact value that you want to plot and then use the `sc.pl.tsne()` call with that field. For example:
```
adata.obs['gene_AB'] = adata[:,'geneA'].X + adata[:,'geneB'].X
sc.pl.tsne(adata, color='gene_AB')
```

However you should consider what you are actually trying to plot first. Maybe you don't just want to add the two values. Other alternatives are first scaling, then adding (to add z-scores). You may not want to scale your whole data, so that would require making a copy of `adata` to do this. Alternatively you can use `sc.tl.score_genes()` as well. That takes the sum of the expression values and subtracts the sum of 2 random genes.

**Comment by koalap-2018** [comment]
Thanks for the quick response. Sounds lie the sc.tl.score_genes()  function will help me too figure things out too.

**Comment by LuckyMD** [comment]
In the future this type of question is probably better suited to the scanpy discourse group:
https://scanpy.discourse.group/

**Comment by chris-rands** [comment]
I arrived here looking for a similar thing, but rather than summing the 2 genes, I'm converting them to binary expressed vs. not expressed combinations. For now i use this approach, but there might be a better approach

```
def plot_2_genes(gene1, gene2):
    pairs_d = {(True, True): "Both expressed",
               (True, False): f"{gene1} not {gene2}",
               (False, True): f"{gene2} not {gene1}",
               (False, False): "Neither expressed"}
    adata_support.obs[f"{gene1}_{gene2}"] = [pairs_d[x] for x in
                                             zip(adata_support[:, gene1].X > 0, adata_support[:, gene2].X > 0)]
    sc.pl.draw_graph(adata_support, color=f"{gene1}_{gene2}")
```

**Comment by paolabc** [comment]
Hi there!

I already have the average gene expression. I have two sets, each one contains 2 genes (example: gene_AB and gene_CD). I am trying to plot them together. However, it gave me two separate plots when I plotted. Is there a way to plot both in the same plot using sc.pl.velocity_embedding_stream or another function?

```
sc.pl.velocity_embedding_stream(adata, basis="tsne",color=['gene_AB','gene_CD'], linewidth=2, scale=2)
```

Thanks
